### ISSUE TITLE
Analytics doesn't work on an Android device

### ISSUE THREAD

**Issue by gnout** [TobiasBuchholz/Plugin.Firebase#10]
I was trying to use FireBase Analytics. I wasn't able to make it work.
Firebase console doesn't recognize the running app.
I initialize the package by calling `CrossFirebase.Initialize(this, savedInstanceState, CreateCrossFirebaseSettings());` and also I set the `googleRequestIdToken`
Calling the  `CrossFirebaseAnalytics.Current.LogEvent("MyEvent"`, parameters); doesn't do anything

**Comment by TobiasBuchholz** [comment]
What do you mean by "doesn't do anything"? 
Did you checkout the Debug View in the project console? 
Is the Analytics Debug Mode enabled on your device? You can do that by executing the following command:

```adb shell setprop debug.firebase.analytics.app <your_package_name>```

[Click here](https://firebase.google.com/docs/analytics/debugview?hl=en) for more information.

**Comment by gnout** [comment]
@TobiasBuchholz By "doesn't do anything" I mean that I do not see data from the app in Firebase console (even after days)
I'm the only user of the app so I should be able to see that there is 1 user in Firebase Console for the Analytics. I sent some events but the Firebase Console Analytics events are empty.
Yes, I did check the debug view but nothing there.
I'm developing the app by using a physical device.
I will try the `adb shell setprop debug.firebase.analytics.app <your_package_name>` that you proposed

**Comment by gnout** [comment]
@TobiasBuchholz Unfortunately, I still don't get any events, even after executing the command that you proposed.

![image](https://user-images.githubusercontent.com/5103845/114375514-031b2b80-9b85-11eb-8f0f-bb2ef4483a90.png)

**Comment by gnout** [comment]
@TobiasBuchholz A few more details regarding the issue

Seems that the firebase instance is is not initialize although I did use the initialization code that I found in your examples
![image](https://user-images.githubusercontent.com/5103845/114379462-22b45300-9b89-11eb-9d0b-275458f38c0c.png)

This is the initialization code that I have
![image](https://user-images.githubusercontent.com/5103845/114379845-9d7d6e00-9b89-11eb-8823-fb37b7055d52.png)

The `googleRequestIdToken` is taken from the following
![image](https://user-images.githubusercontent.com/5103845/114379666-5d1df000-9b89-11eb-8dbc-d4e84548c122.png)

**Comment by TobiasBuchholz** [comment]
Did you try to add the Xamarin.Firebase.Analytics package explicitly to your project file?

```xml 
<PackageReference Include="Xamarin.Firebase.Analytics" Version="118.0.2" />
```

**Comment by gnout** [comment]
@TobiasBuchholz No I haven't, but I will try to do that
