### ISSUE TITLE
Add isFromCache from Metadata

### ISSUE THREAD

**Issue by SeriousM** [TobiasBuchholz/Plugin.Firebase#101]
Hi! Please add the property isFromCache from the native sdks into the metadata object as it's available and important to us.

* Android: https://github.com/firebase/firebase-android-sdk/blob/master/firebase-firestore/src/main/java/com/google/firebase/firestore/SnapshotMetadata.java#L32
* iOS: https://github.com/firebase/firebase-ios-sdk/blob/master/Firestore/Source/API/FIRSnapshotMetadata.mm#L60

Thank you very much!

**Comment by TobiasBuchholz** [comment]
Hoi, I've created a new version of the plugin 1.2.4 which contains this property ✌️

**Comment by SeriousM** [comment]
Superb, thank you!
