### ISSUE TITLE
How to access firestore's FieldPath.DocumentId()?

### ISSUE THREAD

**Issue by AdamBebko** [TobiasBuchholz/Plugin.Firebase#105]
I'm looking to filter a query by documentID, but I can't seem to find a way to access `FieldPath.DocumentId()`. I can see it exists in the native plugins, but it doesn't seem to be accessible from `CrossFirebaseFirestore`

Any ideas on this? I thought of using platform specific code to return the path, but it didn't work because the method returns a `FieldPath` object, rather than a string or something interchangeable.

Any ideas on how this might be possible?

**Comment by TobiasBuchholz** [comment]
Hmm, actually there is a `DocumentId()` method on the plugins shared [FieldPath](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/97e254870ea7765eed20eaaac51c4fa3b44d79dd/src/Shared/Firestore/FieldPath.cs#L16) class, so you can just use it in a query like this:

```c#
var pokemons = await sut
    .GetCollection("pokemons")
    .WhereFieldIn(FieldPath.DocumentId(), new object[] { "1", "2", "3" })
    .GetDocumentsAsync<Pokemon>();

```
