### ISSUE TITLE
[iOS] calling completion in didReceiveNotificationResponse:completionHandler

### ISSUE THREAD

**Issue by shinya-terasaki** [TobiasBuchholz/Plugin.Firebase#106]
Thank you for publishing the library.

May I ask one point?

I got a following warning in an iOS app when I processed an in-coming notification.
> Warning: UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called.

May I ask that completionHandler is not need to be called in userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: ?

https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/src/iOS/CloudMessaging/FirebaseCloudMessagingImplementation.cs#L75-L83

According to the [API document](https://developer.apple.com/documentation/usernotificationsui/unnotificationcontentextension/1845197-didreceivenotificationresponse), 
> The block to execute when you are finished performing the action. You must call this block at some point during your implementation.

Since it is warning, it may not have a big impact though.

**Comment by TobiasBuchholz** [comment]
At least for me it didn't have any impact so far. Nevertheless I've created a [fix](https://github.com/TobiasBuchholz/Plugin.Firebase/commit/e3fd42f858464082d46e558c8ca08093919e51a4) for that so in the next plugin version it will be included and the error message shouldn't appear anymore.
