### ISSUE TITLE
Need testing with iOS simulator

### ISSUE THREAD

**Issue by binhtt6** [TobiasBuchholz/Plugin.Firebase#107]
Hello, is there any one try this library with iOS simulator?
I tested with Android using MAUI blazor and everything is fine.
But no luck with iOS simulator and device.
Thanks

**Comment by TobiasBuchholz** [comment]
I have developed the library using an iOS simulator, so it should basically work. I haven't tried it with an MAUI blazor app yet, but I don't know a reason why it shouldn't work as well. What kind of problem do you have?

**Comment by binhtt6** [comment]
![image](https://user-images.githubusercontent.com/30441291/210790974-95caf8bd-6cde-428b-942e-5b188e6094e7.png)
Hi, i put this, and it worked in android but in ios, i can not get firebase id although  GoogleService-Info.plist is added

**Comment by vIceBerg** [comment]
Here's another detail. The AppShell.OnAppearing method gets called before the iOS.FinishedLaunching event is triggered. That's why I think we get an exception. 

So the code in MauiProgram:

`
events.AddiOS(iOS => iOS.FinishedLaunching((app, launchOptions) =>
{
	CrossFirebase.Initialize(app, launchOptions, CreateCrossFirebaseSettings());
	return false;
}));
`

Is called after we use the service in the OnAppearing method

**Comment by binhtt6** [comment]
HI, it will try again and tell you the result. thanks

**Comment by kirakosyan** [comment]
hi 
I have similar issue. All is great with Android. When testing with iOS real device getting this

{System.NullReferenceException: Object reference not set to an instance of an object.    at Plugin.Firebase.CloudMessaging.FirebaseCloudMessagingImplementation.GetTokenAsync()    at MobileAppX.App.OnStart() in }	

It is called from App.xaml.cs in MAUI app

**Comment by tranb3r** [comment]
I'm using `WillFinishLaunching` instead of `FinishedLaunching` and I do not have this kind of issue.
Maybe you should try it.
