### ISSUE TITLE
Calling GetDownloadUrlAsync() when Offline causes an internal endless loop

### ISSUE THREAD

**Issue by rgiurea** [TobiasBuchholz/Plugin.Firebase#11]
Hi, thanks for the great plugin and your dedication. 
I use the plugin and until now it works like a charm.

So I was trying (on Android only until now) to call the function `IStorageReference.GetDownloadUrlAsync()` on a valid storage reference. Problem is that when I am offline with my phone, the call gets stucked in the await and I see this  log message.
`E/StorageUtil: error getting token java.util.concurrent.ExecutionException: com.google.firebase.internal.api.FirebaseNoSignedInUserException: Please sign in before trying to get a token.`
I think here you should retry maybe 2-3 time (configurable) and if it fails then just return a null url or throw an exception. I prefer null url. Then the app would know that something went wrong and do its thing.
Of course I could check before I do the call if I have internet, but what if after 1ms I don't, it still fails.
Also.. at the moment if you stay to much offline it retries endless and fails with this exception after about 1-2 minutes 
```
Firebase.Storage.StorageException: The operation retry limit has been exceeded. ---> Java.Net.SocketException: Network subsystem is unavailable
   --- End of inner exception stack trace ---
  at Plugin.Firebase.Android.Storage.StorageReferenceWrapper.GetDownloadUrlAsync () [0x00067] in <f4f01eae19504ae384c3bd038d85e937>:0 
...
```

Let me know if I can help. Thanks.

**Comment by TobiasBuchholz** [comment]
The exception messages you are seeing in the logs are created in the native SDK and the error doesn't get populated, so unfortunately there is not a lot I can do about it. To keep the plugin's code as close as possible to the native code I prefer to not add any extra workaround functionality (at least for now).

The only solution to your problem I can think of is to add a progress observer to the StorageTransferTask and cancel after a specific timeout when the progress doesn't get emitted. Something like this:

``` c#
var tcs = new TaskCompletionSource<bool>();
var task = reference.DownloadFile($"path/to/file.txt");

task.AddObserver(StorageTaskStatus.Success, _ => tcs.SetResult(true));

task.AddObserver(StorageTaskStatus.Progress, snapshot => {
    // some timeout logic that calls tcs.SetResult(false)
});
            
await tcs.Task;
```

Hope this helps :)

**Comment by rgiurea** [comment]
OK, thanks for quick response. I will try to work around the issue with what you purpose. Cheers.
