### ISSUE TITLE
Support for Firebase In-App Messaging

### ISSUE THREAD

**Issue by raver99** [TobiasBuchholz/Plugin.Firebase#112]
First of all great plugin, it is really helpful to have a wrapper for all these Firebase features.

Unfortunately, In-App Messaging is not working, even if I add the appropriate SDK "Xamarin.Firebase.InAppMessaging".

In the playground project, when I add the nuget previously mentioned to the Android project, there is the following build time error:

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(3,3): Error XA1014: JAR library references with identical file names but different contents were found: __reference__guava.jar. Please remove any conflicting libraries from EmbeddedJar, InputJar and AndroidJavaLibrary. (XA1014) (Playground.Android)

Any ideas on how to support In App Messaging as well? Thanks

**Comment by TobiasBuchholz** [comment]
The In App Messaging Feature is not supported by the plugin yet, so I don't have any exerience regarding to this issue sorry. But maybe the problem could be solved by adding `Xamarin.Google.Guava.ListenableFuture` explicitly with excluded assets like it was necessary for the [legacy version of the plugin](https://github.com/TobiasBuchholz/Plugin.Firebase#android-specifics-1):

```c#
<PackageReference Include="Xamarin.Google.Guava.ListenableFuture" Version="1.0.0.2" ExcludeAssets="build;buildTransitive" />
```

Hope this helps!

**Comment by TobiasBuchholz** [comment]
Since I haven't heard from you in more than 30 days, I hope this issue is no longer affecting you. If it is, please reopen this issue and provide the more information so that I can look into it further. Thank you!
