### ISSUE TITLE
Google Sign In Dialog Opens Up-When Selecting Account not able to listen back or get the user information

### ISSUE THREAD

**Issue by priyarishi** [TobiasBuchholz/Plugin.Firebase#113]
I have a view with Button called Sign in using Google.
When I click on it and call the plugin service function. The Google SSO Dialog Opens fine . 
When I select the account I want to login as , the control never comes back to the app. 
Dont know how to get the user I selected . Need Urgent help please.

**Comment by TobiasBuchholz** [comment]
Google's dialog should close automatically after you've signed in successfully. The `SignInWithGoogleAsync()` mehtod returns an instance of `IFirebaseUser` and since it's an async method you need to use the `await` keyword to receive it.

**Comment by priyarishi** [comment]
@TobiasBuchholz  Also the capturing of the event in the MainActivity.cs ( which you have rightly mentioned in the auth docs)

   protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
    {
        base.OnActivityResult(requestCode, resultCode, data);
        FirebaseAuthImplementation.HandleActivityResultAsync(requestCode, resultCode, data);
    } 

If the key to getting the control back to the app. And then the Firebase User instance will have all the information about user.

**Comment by priyarishi** [comment]
@TobiasBuchholz I am facing issues running this app on Iphone . After I have installed Plugin.Firebase.
Is this supported on iphone? Error is as below
[0:] An error occurred: 'Could not resolve type with token 010000a6 from typeref (expected class 'Firebase.Auth.IAuthUIDelegate' in assembly 'Firebase.Auth, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')'. Callstack: '   at System.Reflection.RuntimeModule.GetTypes()

**Comment by TobiasBuchholz** [comment]
Since I haven't heard from you in more than 30 days, I hope this issue is no longer affecting you. If it is, please reopen this issue and provide the more information so that I can look into it further. Thank you!
