### ISSUE TITLE
Firestore: auto upload of ServertimerTimestamp with an attribute

### ISSUE THREAD

**Issue by Mataboge** [TobiasBuchholz/Plugin.Firebase#12]
Hi

It would be very useful to have an attribute feature that uploads a FieldValue.ServerTimestamp() instead of the local property value to Firestore when performing a write function, and read the stored value when performing a read.

An example of this can be seen [here](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/datamodel.html#server-side-timestamp) on the .Net Firestore implementation.

An example implementation could be something like this

`public class HighScore : IFirestoreObject
  {

      [FirestoreProperty("Score")]
      public int Score { get; set; }
  
      [FirestoreProperty("Name")]
      public string Name { get; set; }
  
      [FirestoreProperty("LastUpdated"), ServerTimestamp]
      public DateTimeOffset LastUpdated { get; set; }
  }`

When performing a write, the LastUpdated property uploads a FieldValue.Servertimestamp() while the read is as normal.

**Comment by Kapusch** [comment]
Very good idea, this can be useful to get the update date or creation date of a document

**Comment by Kapusch** [comment]
Or maybe could we somehow populate the fetched document Metadata with these two "UpdateDate" and "CreationDate" ?
[Google Firestore "RPC" documentation](https://cloud.google.com/firestore/docs/reference/rpc/google.firestore.v1#document)

**Comment by Mataboge** [comment]
Has there been any development regarding this?
