### ISSUE TITLE
[Plugin.Firebase]: Couldn't attach image to push notification

### ISSUE THREAD

**Issue by iwontknow** [TobiasBuchholz/Plugin.Firebase#123]
Hey there, i tried to implement this Plugin in my MAUI project.
When i send an push notification (topic based) via my server, it always tells me, even though i dont even have an image attached.
`[DOTNET] [Plugin.Firebase]: Couldn't attach image to push notification: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference`
Maybe im just slow or confused but it wont receive the notification due to that. 

Side Note:
Receiving Notifications via Token is working.

**Comment by tranb3r** [comment]
I'm having the same issue.
The workaround consists in using the NotificationBuilderProvider and setting your own builder according to your needs.
https://github.com/TobiasBuchholz/Plugin.Firebase/blob/81fdff2e38f9d9529ee7ecc676dab2408b19fea5/src/Android/CloudMessaging/FirebaseCloudMessagingImplementation.cs#LL24C73-L24C100

**Comment by TobiasBuchholz** [comment]
See https://github.com/TobiasBuchholz/Plugin.Firebase/issues/156#issuecomment-1498107791
