### ISSUE TITLE
How to disable bitcode strip in Plugin.Firebase.It causing issue in iOS in .net MAUI.

### ISSUE THREAD

**Issue by deepikacis** [TobiasBuchholz/Plugin.Firebase#126]
I am facing below issue for GoogleAppMeasurement in iOS when making release build  :
C:\Users\abc\.nuget\packages\xamarin.firebase.ios.core\8.10.0.3\buildTransitive\Xamarin.Firebase.iOS.Core.tar
gets(216,5): error MSB3073: The command ""$(xcrun -find bitcode_strip)" C:/Users/abc/AppData/Local/XamarinBui
ldDownloadCache/GAppM-8.9.1/GoogleAppMeasurement-8.9.1/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/Goog
leAppMeasurement.framework/GoogleAppMeasurement -r -o C:/Users/abc/AppData/Local/XamarinBuildDownloadCache/GA
ppM-8.9.1/GoogleAppMeasurement-8.9.1/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_armv7/GoogleAppMeasurement.f
ramework/GoogleAppMeasurement" exited with code 1. [D:\iOSNotification\iOSNotification\iOSNotification.csproj::TargetFr
amework=net7.0-ios]

I have tried the workaround https://github.com/dotnet/maui/issues/10989 but still facing  below issue for Google Sign In :
D:\MauiFirebaseDemo-master\MauiFirebaseDemo\MauiFirebaseDemo.csproj(148,3): error MSB3073: The command ""$(xcrun -find
bitcode_strip)" C:/Users/abcd/AppData/Local/XamarinBuildDownloadCache/GSgnI-5.0.2/Frameworks/GoogleSignIn.fram
ework/GoogleSignIn -r -o C:/Users/abcd/AppData/Local/XamarinBuildDownloadCache/GSgnI-5.0.2/Frameworks/GoogleSi
gnIn.framework/GoogleSignIn" exited with code 1. [TargetFramework=net7.0-ios]

**Comment by TobiasBuchholz** [comment]
Dupliceate #95
