### ISSUE TITLE
Firestore: simple compound query not working on iOS

### ISSUE THREAD

**Issue by Mataboge** [TobiasBuchholz/Plugin.Firebase#13]
Simple query crashing on iOS 

tested the two function below, and both crashed with error : 
`NullreferenceException: NSvalue cannot be null`

the functions tested:

`Collection.WhereGreaterThan("property", value).GetDocumentsAsync<myObject>();`

`Collection.WhereGreaterThanOrEqualsTo("property", value).GetDocumentsAsync<myObject>();`

The equivalent works perfect on android with the same information.

**Comment by TobiasBuchholz** [comment]
The exception gets thrown inside of the Xamarin.Firebase.iOS.CloudFirestore package, so I'm afraid there is not much I can do about it. 

What are you trying to accomplish with your query or what kind of object is `value`? I guess these methods are only working well with number or string values. One of the tests in [FirestoreTestFixture](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/496357362df4795e876ef58f16213252e74eb5d7/tests/Plugin.Firebase.IntegrationTests/Firestore/FirestoreFixture.cs#L132) uses these methods and is working fine on android and iOS.

```c#
[Fact]
 public async Task gets_data_with_compound_query()
{
    var sut = CrossFirebaseFirestore.Current;
    var collection = sut.GetCollection("pokemons");
            
    var smallWaterPokemons = await collection
        .WhereEqualsTo("poke_type", PokeType.Water)
        .WhereGreaterThanOrEqualsTo("height_in_cm", 50)
        .WhereLessThan("height_in_cm", 100)
        .GetDocumentsAsync<Pokemon>();
            
    Assert.Single(smallWaterPokemons.Documents);
}
```

**Comment by Mataboge** [comment]
_value_ is of type **DateTimeOffset** , it is a timestamp, I use it to as a limiter to fetch documents that changed after a specific time
