### ISSUE TITLE
Cannot create PhoneAuthCredential without eiter verfication proof,sessionInfo, temporary proof,or enrollment ID.

### ISSUE THREAD

**Issue by NullC0d3** [TobiasBuchholz/Plugin.Firebase#132]
this error always shows on release version after user try to pass the otp code for phone auth
project build with xamarin forms

**Comment by TobiasBuchholz** [comment]
Since I haven't heard from you in more than 30 days, I hope this issue is no longer affecting you. If it is, please reopen this issue and provide the more information so that I can look into it further. Thank you!
