### ISSUE TITLE
Couldn't attach image to push notification if the app is in foreground

### ISSUE THREAD

**Issue by RsZoli** [TobiasBuchholz/Plugin.Firebase#133]
If the app is in foreground, there is an exception possibly in the onrecieved function:

[DOTNET] [Plugin.Firebase]: Couldn't attach image to push notification: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference

If the app is in the background, notifications are working just fine:

[FirebaseMessaging] Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.

I'm building against net7.0-android

.NET SDK:
 Version:   7.0.103
 Commit:    276c71d299

.NET SDKs installed:
  7.0.103 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by TobiasBuchholz** [comment]
Hi, did you complete all [android specific](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/docs/cloud_messaging.md#android-specifics) steps from the docs? You can also take a look at the [sample project](https://github.com/TobiasBuchholz/Plugin.Firebase/tree/development/sample/Playground).

**Comment by RsZoli** [comment]
@TobiasBuchholz Hi! As i have mentioned this on the issue, i did these steps but unfortunetly, it still doesn't work!

**Comment by TobiasBuchholz** [comment]
See https://github.com/TobiasBuchholz/Plugin.Firebase/issues/156#issuecomment-1498107791
