### ISSUE TITLE
Plugin.Firebase.Android could not be resolved

### ISSUE THREAD

**Issue by sej69** [TobiasBuchholz/Plugin.Firebase#138]
I see there is one for iOS but I'm not sure it's referencing the same type of issue I'm experiencing on a new .net Maui project.

In my MauiProgram.cs file I am able to add "Using Plugin.Firebase.Android", .Android shows up on the code helper but with a warning triangle on it.  When I look closer at it, it says that it's available.  When selected, I get the CS0234:  the type or namespace name 'Android' does not exist in the namespace 'Plugin.Firebase' ...

This is a .net7 Maui project.  I did back it down to .net6 and got the same error (and more as a lot of the errors were referencing package errors).

**Comment by sej69** [comment]
I can't get that to work for me; I've still got that error.  Sadly, I've got that error now with the iOS version of the plugin too:

using Plugin.Firebase.Bundled.Platforms.iOS;

**Comment by TobiasBuchholz** [comment]
Please provide an example project so I can look into it. Also what OS and Visual Studio version are you using?

**Comment by sej69** [comment]
I'll work on building a sample project, I can't send up the project I'm working with.  

I'm on Win 11, VS2022 - 17.4.3

**Comment by sej69** [comment]
I just discovered that there is an "example" package out there as part of the source for this project.  It appears to be using old libraries, is it possible to update the example?  There's a lot of code in there that is not present on your page here: https://github.com/TobiasBuchholz/Plugin.Firebase#net-maui-support

**Comment by sej69** [comment]
I re-downloaded the library with the samples in it.  It is showing 24 packages out of date but it's not showing the compile errors I was seeing the first time around?  I'll work off of this to see if I can get the notification working; there's a lot more here that's not in the sample. Thanks!

**Comment by TobiasBuchholz** [comment]
Since I haven't heard from you in more than 30 days, I hope this issue is no longer affecting you. If it is, please reopen this issue and provide the more information so that I can look into it further. Thank you!
