### ISSUE TITLE
xamarin.google.guava.listenablefuture providing error NS1605 in a .net Maui project

### ISSUE THREAD

**Issue by sej69** [TobiasBuchholz/Plugin.Firebase#142]
I was having so many issues linking in the plugin.firebase into my active project that I decided to create a new .net Maui project specifically to play with this.  I was following the instructions here:

https://www.andreasnesheim.no/push-notifications-in-net-maui-with-firebase/

and here:

https://github.com/TobiasBuchholz/Plugin.Firebase#net-maui-support

I had to use: "dotnet add package Plugin.Firebase" to install the nuget package

I immediately got the following errors when trying to compile:

Error	MSB4064	The "AndroidFixManifests" parameter is not supported by the "XamarinDownloadArchives" task loaded from assembly: Xamarin.Build.Download, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from the path: C:\Users\sjohnson.MYNET\.nuget\packages\xamarin.build.download\0.11.4\buildTransitive\Xamarin.Build.Download.dll. Verify that the parameter exists on the task, the <UsingTask> points to the correct assembly, and it is a settable public instance property.	NotificationTest	C:\Users\sjohnson.MYNET\.nuget\packages\xamarin.build.download\0.11.0\buildTransitive\Xamarin.Build.Download.targets	60	

Error	MSB4063	The "XamarinDownloadArchives" task could not be initialized with its input parameters. 	NotificationTest	C:\Users\sjohnson.MYNET\.nuget\packages\xamarin.build.download\0.11.0\buildTransitive\Xamarin.Build.Download.targets	52	

Error	NU1605	Detected package downgrade: Xamarin.Google.Guava.ListenableFuture from 1.0.0.9 to 1.0.0.7. Reference the package directly from the project to select a different version. 
 NotificationTest -> Plugin.Firebase 1.3.0 -> Xamarin.AndroidX.Browser 1.4.0.2 -> Xamarin.Google.Guava.ListenableFuture (>= 1.0.0.9) 
 NotificationTest -> Xamarin.Google.Guava.ListenableFuture (>= 1.0.0.7)	NotificationTest	D:\Dev\NotificationTest\NotificationTest.csproj	1	

Error	NU1605	Detected package downgrade: Xamarin.Google.Guava.ListenableFuture from 9999.0.0 to 1.0.0.9. Reference the package directly from the project to select a different version. 
 NotificationTest -> Plugin.Firebase 1.3.0 -> Xamarin.Firebase.Firestore 124.3.1 -> Xamarin.Google.Guava 31.1.0.3 -> Xamarin.Google.Guava.ListenableFuture (>= 9999.0.0) 
 NotificationTest -> Xamarin.Google.Guava.ListenableFuture (>= 1.0.0.9)	NotificationTest	D:\Dev\NotificationTest\NotificationTest.csproj	1	

Error	NU1605	Detected package downgrade: Xamarin.Google.Guava.ListenableFuture from 9999.0.0 to 1.0.0.9. Reference the package directly from the project to select a different version. 
 NotificationTest -> Plugin.Firebase 1.3.0 -> Xamarin.Firebase.Firestore 124.3.1 -> Xamarin.Google.Guava 31.1.0.3 -> Xamarin.Google.Guava.ListenableFuture (>= 9999.0.0) 
 NotificationTest -> Xamarin.Google.Guava.ListenableFuture (>= 1.0.0.9)	NotificationTest	D:\Dev\NotificationTest\NotificationTest.csproj	1	

I noticed the version that was installed during the package manager install was 1.0.0.9 so I updated the line:

<PackageReference Include="Xamarin.Google.Guava.ListenableFuture" Version="1.0.0.7" ExcludeAssets="build;buildTransitive" />

to

<PackageReference Include="Xamarin.Google.Guava.ListenableFuture" Version="1.0.0.9" ExcludeAssets="build;buildTransitive" />

So that error went away.  But, the installed version listed in nuget is still 1.0.0.7.

However, the 9999.0 to 1.0.0.9 doesn't go away so there must be another project referencing this.  

It shows there are three packages available for updates in nuget (coincidentally they are all a part of the plugin.firebase instructions):

Xamarin.Google.Guava.ListenableFuture Installed: 1.0.0.7 available 1.0.0.11
Xamarin.Kotlin.StdLib.Jdk7 installed: 1.7.10 available 1.8.10
Xamarin.Kotlin.StdLib.jdk8 installed: 1.7.10 available 1.8.10

However, I cannot update any of them, nuget throws a whole bunch of errors like this:

Error	NU1202	Package Xamarin.Google.Guava.ListenableFuture 1.0.0.11 is not compatible with net6.0-ios16.1 (.NETCoreApp,Version=v6.0) / android-arm. Package Xamarin.Google.Guava.ListenableFuture 1.0.0.11 supports:
  - monoandroid12.0 (MonoAndroid,Version=v12.0)
  - net6.0-android31.0 (.NETCoreApp,Version=v6.0)	NotificationTest	D:\Dev\NotificationTest\NotificationTest.csproj	1

**Comment by andyzukunft** [comment]
I also get the error
`Error	MSB4064	The "AndroidFixManifests" parameter is not supported by the "XamarinDownloadArchives" task loaded from assembly: Xamarin.Build.Download`
but it doesn't stop me from building and starting the application. So at the moment I tread it as a warning.

Did you try to stop targeting specific Android and iOS version (e.g. just net6.0-ios instead  net6.0ios16.1)?

I think you have to provide your .csproj file so the people can check what kind of conditional build options you have set and if they are configured incorrectly.

**Comment by sej69** [comment]
I removed the lines from the project.cs file and it compiled with no errors, but I haven't had a chance to see if it's working yet.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by andyzukunft** [comment]
Can you clarify which lines you removed from the .cproj file?

**Comment by sej69** [comment]
The whole
<ItemGroup>
…
</ItemGroup>

Listed here:

TobiasBuchholz/Plugin.Firebase: Wrapper around the native Android and iOS Firebase Xamarin SDKs (github.com)<https://github.com/TobiasBuchholz/Plugin.Firebase#net-maui-support>

**Comment by andyzukunft** [comment]
I am still not sure what you removed. If you removed all of the <ItemGroup>-nodes than you also removed those for the google-services.json definition or the one with the Plugin.Firebase nuget definition. This can't work.

**Comment by sej69** [comment]
On that URL, I removed everything between the <itemgroup> tags:

<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'">
  <PackageReference Include="Xamarin.Kotlin.StdLib.Jdk7" Version="1.7.10" ExcludeAssets="build;buildTransitive" />
  <PackageReference Include="Xamarin.Kotlin.StdLib.Jdk8" Version="1.7.10" ExcludeAssets="build;buildTransitive" />
</ItemGroup>


There was another line or two I had in there, too based on other pieces that said which needed to be in there.

**Comment by tranb3r** [comment]
> I also get the error `Error MSB4064 The "AndroidFixManifests" parameter is not supported by the "XamarinDownloadArchives" task loaded from assembly: Xamarin.Build.Download` but it doesn't stop me from building and starting the application. So at the moment I tread it as a warning.

I think this can be fixed by adding this package:
`<PackageReference Include="Xamarin.Build.Download" Version="0.11.4" />`

**Comment by andyzukunft** [comment]
This fixed it indeed! Thanks for the info!

**Comment by sej69** [comment]
@tranb3r Where did you find the version for that?

**Comment by tranb3r** [comment]
> @tranb3r Where did you find the version for that?

0.11.4 is the most recent version.
https://www.nuget.org/packages/Xamarin.Build.Download#versions-body-tab

**Comment by Kapusch** [comment]
Hi, I'm currently migrating my app to .NET MAUI and all I have in my .csproj related to the Plugin is:
`<PackageReference Include="Plugin.Firebase" Version="2.0.3" />`

I have nothing more related to:
-  `xamarin.google.guava.listenablefuture` library,
- neither `Xamarin.Build.Download`
- and any other platform specific Firebase library.

Did you get a try with a fresh .NET MAUI project, and migrate pieces after pieces ?
It takes a long time for sure, but at least, it's safer.

**Comment by andyzukunft** [comment]
Hey,

I can't confirm this at the moment. `Xamarin.Build.Download` still seems to be required. If it is not present you will get a build warning or error which will not stop you from launching your app.

I can concur that I don't use anything else specifically targeting the Firebase library beyond that.

**Comment by TobiasBuchholz** [comment]
Since I haven't heard from you in more than 30 days, I hope this issue is no longer affecting you. If it is, please reopen this issue and provide the more information so that I can look into it further. Thank you!
