### ISSUE TITLE
Microsoft.CSharp dependency

### ISSUE THREAD

**Issue by tranb3r** [TobiasBuchholz/Plugin.Firebase#143]
Hi,

`Microsoft.CSharp` is listed in `Plugin.Firebase` nuget's dependencies.
Do you know why it's referenced in `Plugin.Firebase.csproj`? What is it used for? Can it be removed?

Thanks!

**Comment by TobiasBuchholz** [comment]
I actually can't remember why this dependency is included...removing it doesn't seem to cause any build problems and the tests are fine as well, so I will remove it at the next version 👍

**Comment by TobiasBuchholz** [comment]
Changing the code to not using the `dynamic` keyword anymore wasn't very difficult, so the new version 2.0.1 shouldn't pull in `Microsoft.CSharp` anymore.
