### ISSUE TITLE
[2.0.0] App size increase

### ISSUE THREAD

**Issue by tranb3r** [TobiasBuchholz/Plugin.Firebase#149]
Hi,

I've just tested the 2.0.0 plugin with split features.
I was expecting the app size to decrease (getting rid of facebook sdk and a few firebase features I'm not using).
However, the contrary is happening, my app is increasing by more than 1.5MB, which is somthing I cannot afford.
The reason for this increase is that each split assembly contains tons of android resources (pulled in by maui) that weight a few hundreds of kB, and even more once the assembly is AOT'ed.
Even if I understand your motivation for implementing the split, this is a really annoying side-effect.

I think one solution could be to publish another bundled nuget, containing a single assembly. 
So, the same as before the split. But without facebook sdk.
It should be possible to do that just by writing the proper csproj, right?
And then, we let the trimmer do its magic. It works with 1.x, so there is no reason it should not work with 2.x.

Let me know what you think.
Thanks.

**Comment by tranb3r** [comment]
I've given it some thought, and I think an easy fix is to remove the `UseMaui` property from all `csproj`.
It's Maui that pulls in android resources in each assembly. And actually you don't need Maui in this plugin.
Except in Auth, but here you should probably use `UseMauiEssentials` instead of `UseMaui`.

**Comment by vhugogarcia** [comment]
I just remember a way to probably remove those Android resources when using `<UseMaui>true</UseMaui>` Maybe this can help?

```xml
<PropertyGroup>
      <AndroidGenerateResourceDesigner>false</AndroidGenerateResourceDesigner>
</PropertyGroup>
```

By adding that under each project of the Plugin, in theory those Android resources you mentioned @tranb3r can go away.

**Comment by tranb3r** [comment]
Yeah... I'm not sure it's a good idea to disable `AndroidGenerateResourceDesigner`.
I mean, if there is no reason to have `UseMaui`, just remove it.
The remaining resources... how do you know that they're not needed somewhere, and that it's safe to force remove them?

**Comment by TobiasBuchholz** [comment]
I agree with @tranb3r on this one and will remove `UseMaui` from the csproj files in the next version. Thanks a lot for the feedback and useful hints @tranb3r, really appreciated! :)

**Comment by TobiasBuchholz** [comment]
The new version 2.0.1 with `UseMaui` removed is published now.
