### ISSUE TITLE
[2.0.0] Support net6.0 TFM

### ISSUE THREAD

**Issue by tranb3r** [TobiasBuchholz/Plugin.Firebase#150]
Hi,

The 2.0.0 version of the plugin does not support net6.0 TFM. It only supports net6.0-android and net6.0-ios.
This is not very convenient when one want to add the plugin to a pure net6.0 class library (used in an android/ios app), since it requires to modify the supported TFMs of the class library to make it an android/ios library, which should not be necessary.

Could you please add net6.0 TFM support to the nugets ?

Thanks !

**Comment by vhugogarcia** [comment]
I don't think that is possible and/or necessary. Because, it has platform specific code _(I may be wrong)_. It works very good as it is now. Also, it will requiere to add additional code and it will lead to generate large file size.

**Comment by tranb3r** [comment]
@vhugogarcia Thank you for you comment, but you're wrong.
First, it's possible. Of course it has platform specific code. But this does not prevent it from referencing it from a pure net6.0 project.
Second, it's necessary. It's pretty much how every dotnet maui plugin is implemented. Including the previous version of this plugin.
About file size, I honestly doubt it will make any visible difference, because the pure dotnet assembly is replaced by the platform specific version of the assembly when building the application, so in the end you have the same application code.

**Comment by vhugogarcia** [comment]
Thanks for the explanation @tranb3r . I keep learning new stuff everyday, and it makes sense now that I think of more in depth.

I believe it will also worth to upgrade to .NET 7 the projects, maybe? what do you think?

**Comment by tranb3r** [comment]
> I believe it will also worth to upgrade to .NET 7 the projects, maybe? what do you think?

Why do you want to upgrade to net7?
It's important to support net6 since it's LTS.

**Comment by vhugogarcia** [comment]
> > I believe it will also worth to upgrade to .NET 7 the projects, maybe? what do you think?
> 
> 
> 
> Why do you want to upgrade to net7?
> 
> It's important to support net6 since it's LTS.

If you think about it more in depth, on mobile world the .NET version is irrelevant if LTS or STS, because you must upgrade yes or yes due to an iOS and Android guidelines.

However, the benefit to upgrade is the performance on common .NET tasks like managing strings, lists, and platform improvements, etc. 

Again, I may be wrong. I am just sharing my grain of salt.

**Comment by TobiasBuchholz** [comment]
> >I believe it will also worth to upgrade to .NET 7 the projects, maybe? what do you think?
>
> Why do you want to upgrade to net7?
> It's important to support net6 since it's LTS.


I agree with that, so the plugin should stay at .net6 until it's really necessary to update to .net7.

The .net6.0 TFM was removed by accident and I don't think there is any harm in adding it back in, so I will do that for next version so people like @tranb3r can benefit from it :)
