### ISSUE TITLE
Unable to install plugin (some filepaths exceeds 260 character)

### ISSUE THREAD

**Issue by DanielMuhlig** [TobiasBuchholz/Plugin.Firebase#153]
Trying to install the Plugin.Firebase plugin from Nuget manager in Visual Studio 2022 on Windows 10, I get the following error:

Could not find a part of the path 'C:\Users\Daniel\.nuget\packages\xamarin.firebase.ios.core\8.10.0.1\lib\net6.0-ios15.4\Firebase.Core.resources\GoogleUtilitiesComponents.xcframework\ios-arm64_i386_x86_64-simulator\GoogleUtilitiesComponents.framework\Headers\GoogleUtilitiesComponents-umbrella.h'.

I have tried to set the Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled to 1 (to allow filepaths beyond the default 260 characters) but it didn't have any effect.

I then set the NUGET_PACKAGES environment variable to "E:\Nugets" to make the path shorter, but that only resulted in the error moving to another file:

Could not find a part of the path 'E:\Nugets\xamarin.firebase.ios.cloudfirestore\8.10.0.3\lib\xamarinios10\Firebase.CloudFirestore.resources\grpcpp.xcframework\ios-arm64_x86_64-simulator\grpcpp.framework\PrivateHeaders\src\core\ext\filters\client_channel\lb_policy\grpclb\client_load_reporting_filter.h'.

How do I install the nuget package?

**Comment by TobiasBuchholz** [comment]
Have you tried to install it with `dotnet add package Plugin.Firebase`?

**Comment by DanielMuhlig** [comment]
Thank you. It worked :-)
