### ISSUE TITLE
iOS Bitcode problem in Plugin.Firebase.Auth

### ISSUE THREAD

**Issue by tetzschner** [TobiasBuchholz/Plugin.Firebase#158]
Hi

Please change Plugin.Firebase.Auth dependency version for Xamarin.Google.iOS.SignIn from >=5.0.2.3 to >=5.0.2.4.

I've been struggling for days with iOS release (rejected because bitcode in AppAuth and GTMAppAuth). All Facebook auth was removed from my code and I'm only using Plugin.Firebase.CloudMessaging and Plugin.Firebase.Auth.

After manually installing Xamarin.Google.iOS.SignIn 5.0.2.4 Apple is now accepting the iOS release in AppStore (and SMS auth is now working).

Regards Ole

**Comment by TobiasBuchholz** [comment]
Thanks for the hint, I've updated this dependency in version Plugin.Firebase.Auth 2.0.2 ✌️
