### ISSUE TITLE
Create User

### ISSUE THREAD

**Issue by donniefitz2** [TobiasBuchholz/Plugin.Firebase#16]
Am I missing something, or is `CreateUserAsync(string email, string password)` missing from the shared project?

I see it exists in both platform projects, but it's not exposed in the shared project.

**Comment by TobiasBuchholz** [comment]
The user actually gets created automatically when the `SignInWithEmailAndPasswordAsync(email, password)` is called and the user doesn't exist. 

I've created a new version 1.0.8 which exposes the `CreateUserAsync(email, password)` method now. I've also added a boolean flag to the signIn-method, so you can choose whether a user gets created automatically or not. If you choose not to ceate it automatically an exception gets thrown instead.

**Comment by donniefitz2** [comment]
Okay, cool. That makes sense. I should have looked further into it. Thanks for the followup.
