### ISSUE TITLE
 CrossFirebaseCloudMessaging.Current.GetTokenAsync() can't catch exception

### ISSUE THREAD

**Issue by podg999** [TobiasBuchholz/Plugin.Firebase#164]
So I first call 
await CrossFirebaseCloudMessaging.Current.CheckIfValidAsync();
and then
var token = await CrossFirebaseCloudMessaging.Current.GetTokenAsync();

but nothing happens, doesn't throw exception just stops debugging after few minutes.

Tested on 2 different androids with 2 different API-s (31, 33) and nothing works.

**Comment by TobiasBuchholz** [comment]
Could you provide a sample project? Otherwise it's hard to identify the problem based on two lines of code.

**Comment by podg999** [comment]
> Could you provide a sample project? Otherwise it's hard to identify the problem based on two lines of code.

yes, https://github.com/podg999/TestAppMauiPushNotifications

i then used https://github.com/andreas-nesheim/MauiFirebasePush with 1.2.0 Firebase version and got it to work for my needs
