### ISSUE TITLE
Android: The current Activity can not be detected

### ISSUE THREAD

**Issue by gianox** [TobiasBuchholz/Plugin.Firebase#165]
"The current Activity can not be detected." happens as long as the POST_NOTIFICATIONS permission has not yet been accepted by the user. Crashes the app. If using the current workaround:

ActivityCompat.RequestPermissions(this, new[] { Android.Manifest.Permission.PostNotifications }, 0);

You still get a crash - but only on the first time starting, where the user has to accept the permission. If the user does not accept the permission, it will keep crashing the app.

![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/12375291/36ca6879-6c8d-4f8a-a557-f601289186ae)

**Comment by TobiasBuchholz** [comment]
I can't reproduce this behavior. Since I haven't heard from you in more than 30 days, I hope this issue is no longer affecting you. If it is, please reopen this issue and provide a sample project so that I can look into it further. Thank you!
