### ISSUE TITLE
Wrong events sequencing order when initializing the Plugin on iOS

### ISSUE THREAD

**Issue by Kapusch** [TobiasBuchholz/Plugin.Firebase#166]
Hi @TobiasBuchholz !

I'm now migrating my app to MAUI, and I have noticed a different behavior between Android & iOS when initializing your Plugin.
Currently, you're suggesting to register Firebase services in _MauiProgram.cs_ using `ConfigureLifecycleEvents()`:
```
public static class MauiProgram
{
    ...
    private static MauiAppBuilder RegisterFirebaseServices(this MauiAppBuilder builder)
    {
        builder.ConfigureLifecycleEvents(events => {
#if IOS
            events.AddiOS(iOS => iOS.FinishedLaunching((_,__) => {
                CrossFirebase.Initialize();
                return false;
            }));
#else
            events.AddAndroid(android => android.OnCreate((activity, _) =>
                CrossFirebase.Initialize(activity)));
#endif
        });
        ...
        return builder;
    }
}
```

However, from the [documentation](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/app-lifecycle#ios), `iOS.FinishedLaunching()` means the app has **already launched**,  while I understand `android.OnCreate()` it means the activity is created, but startup is NOT completed.

I've been doing some tests and I think the equivalent of `android.OnCreate()` for iOS is `iOS.WillFinishLaunching()`.
Indeed, this solved an issue in my app where "Firebase is not yet configured" while I'm fetching Remote settings from the _App.xaml.cs_ `OnStart()` method.

One more clue is that, while working with the Xamarin.Forms version of your Plugin, we had to initialize the Firebase services from _AppDelegate.cs_ on iOS, inside `FinishedLaunching()` method, NOT after.

Am I wrong doing this ?

**Comment by angelru** [comment]
I think the same thing happens to me on iOS, the plugin "takes time to start". Sometimes I got an exception when using this code at startup:

```
CrossFirebaseCloudMessaging.Current.CheckIfValidAsync();
CrossFirebaseCloudMessaging.Current.SubscribeToTopicAsync("Topic");
```

Because firebase was not started. I had to put the above code in the `OnAppearing `of one of my views and problem solved. Are you experiencing the same problem?

**Comment by TobiasBuchholz** [comment]
Hey @Kapusch, I didn't have any problems when initializing the plugin the way I've described in the Readme, but I think you are completely right that initializing it in `iOS.WillFinishLaunching()` is more similar to the startup process on android and also to the plugin version before Maui 👍

If there is noone who has a case against putting the initialization call in `iOS.WillFinishLaunching()` I will update the Readme accordingly.

**Comment by tranb3r** [comment]
I'm also using `WillFinishLaunching` instead of `FinishedLaunching`.
