### ISSUE TITLE
Problem importing Plugin.Firebase to .MAUI project

### ISSUE THREAD

**Issue by MohammedAlawna** [TobiasBuchholz/Plugin.Firebase#169]
Hi. Whenever I try to install the "Plugin.Firebase" to my project (.NET MAUI) it throws an error to my console:
(The error is shown in the attached image below this thread/issue)
Note that I've enabled "Long Paths" from policy settings, but still the issue persists.
![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/88289155/c85e1810-9982-4feb-9bad-bf321e8a04fc)

**Comment by TobiasBuchholz** [comment]
Hi @MohammedAlawna, did you try to add the package via `dotnet add package Plugin.Firebase`? See https://github.com/TobiasBuchholz/Plugin.Firebase/issues/65 for more information.

**Comment by JamesSonic** [comment]
I've added my package via the CLI but I get the same error when i try to publish the android app. Is there a work around for that issue?

**Comment by BFuchshofer** [comment]
What worked for me was to not use the nuget restore of Visual Studio 22. I used a local nuget.exe inside my project. Download the file from nuget.com and copy next to your solution file. Then use the command "nuget.exe restore". In my case, Plugin.Firebase was restored.

**Comment by MasonWray** [comment]
@MohammedAlawna Try using [Nuget.config](https://stackoverflow.com/questions/77108140/is-it-possible-to-install-xamarin-firebase-ios-cloudmessaging-in-a-maui-app). This worked for me, but be warned, I don't think this package supports .NET 7 yet. I can't get it to deploy, at least.

**Comment by TobiasBuchholz** [comment]
Since I haven't heard from you in more than 30 days, I hope this issue is no longer affecting you. If it is, please reopen this issue and provide the more information so that I can look into it further. Thank you!
