### ISSUE TITLE
Cloud Messaging - Isn't FirebaseInstanceService Depreciated in Favor of FirebaseMessagingService?

### ISSUE THREAD

**Issue by Thomr77** [TobiasBuchholz/Plugin.Firebase#171]
Hi,

I have just been working through the Cloud Messaging documentation and noticed that there are receiver definitions for the AndroidManifest (which you also find in the (old) Xamarin documentation):
```
  <receiver
    android:name="com.google.firebase.iid.FirebaseInstanceIdInternalReceiver"
    android:exported="false" />
  <receiver
    android:name="com.google.firebase.iid.FirebaseInstanceIdReceiver"
    android:exported="true"
    android:permission="com.google.android.c2dm.permission.SEND">
    <intent-filter>
      <action android:name="com.google.android.c2dm.intent.RECEIVE" />
      <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
      <category android:name="${applicationId}" />
    </intent-filter>
  </receiver>
```
Isn't the FirebaseInstanceIdService depreciated and replaced with the FirebaseMessagingService - so these receiver definitions are no longer necessary?

[Google's FirebaseInstanceIdService Reference (where this is mentioned)](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService)

[Xamarin FCM Reference](https://learn.microsoft.com/en-us/xamarin/android/data-cloud/google-messaging/remote-notifications-with-fcm?tabs=macos)

Please let me know - thanks!

**Comment by TobiasBuchholz** [comment]
Hey @Thomr77, the plugin is using the newer [FirebaseMessagingService](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/src/CloudMessaging/Platforms/Android/MyFirebaseMessagingService.cs) already and the other code you are referring to in the `AndroidManifest.xml` are other receiver definitions and should still be necessary as fas as I know.

**Comment by Thomr77** [comment]
Hey @TobiasBuchholz - Okay excellent. Thank you for clearing this up!
Vielen Dank!
