### ISSUE TITLE
Possible nullpointer

### ISSUE THREAD

**Issue by rgiurea** [TobiasBuchholz/Plugin.Firebase#18]
Hi,

there might be a nullpointer in the TrackEvent Method. I attached the stack trace maybe you can locate it.

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
at Plugin.Firebase.Analytics.FirebaseAnalyticsImplementation.LogEvent (System.String eventName, System.Collections.Generic.IDictionary2 [TKey,TValue] parameters)`

Thanks!

**Comment by TobiasBuchholz** [comment]
Hi, could you please provide a bit more information about how you are calling the LogEvent() method and at which platform this exception is occuring?

**Comment by rgiurea** [comment]
Sadly this nullpointer occured in the crashlitics, so I don't have more. I will close this and keep an eye on it. When I understand it better I will open an issue again.
