### ISSUE TITLE
[Android] Conflicts in packages

### ISSUE THREAD

**Issue by EdwardMcFlurry** [TobiasBuchholz/Plugin.Firebase#180]
It seems like this Plugin has a lot of other dependencies that are clashing/conflicting with others from a different Plugin, in this case a Plug-in for AdMob.

@TobiasBuchholz is this something that you are aware of?

**Comment by TobiasBuchholz** [comment]
Hi @EdwardMcFlurry,
yes, there is already issue #172 describing the problem with the Plugin-in for AdMob, but unfortunately I wasn't able to find a solution yet.
