### ISSUE TITLE
[Question] [Firebase Authentication] Is it possible to return the User Id when creating a new account?

### ISSUE THREAD

**Issue by vhugogarcia** [TobiasBuchholz/Plugin.Firebase#183]
Hello @TobiasBuchholz ,

I'm wondering if it is possible for the method:` CrossFirebaseAuth.Current.CreateUserAsync(email, password);` to return the UserId generated.

<img width="680" alt="image" src="https://github.com/TobiasBuchholz/Plugin.Firebase/assets/1047398/dd521a6b-c3d5-4529-b9ab-47a017894723">

If not possible, do you know if there is a method to return a UserId of a user by email and password without needing to authenticating first?

Thanks in advance

**Comment by TobiasBuchholz** [comment]
Hi @vhugogarcia, I've just released a new version 2.0.3 of the Auth package that has the `CrossFirebaseAuth.Current.CreateUserAsync(email, password)` method return an `IFirebaseUser` instance ✌️

**Comment by vhugogarcia** [comment]
Thank you so much for the faster response @TobiasBuchholz really appreciate it 😃. I will give it a try today.
