### ISSUE TITLE
Android Notification custom implementation

### ISSUE THREAD

**Issue by hemant-mobmaxime** [TobiasBuchholz/Plugin.Firebase#21]
First of the all, the library is great. Helps me to implement most of the firebase functionality in my app.

My only concern is when I send multiple notification in android, it's shows multiple notifications in notification bar & history. Is there a way that I can extend/exclude the service & create my notification customisation?

Or it would be a better to add grouping of the notification when multiple notification appears just like gmail handles it.

**Comment by TobiasBuchholz** [comment]
Hi, thanks and sorry for the late response. The android `﻿FirebaseCloudMessagingImplementation` class contains a static property `NotificationBuilderProvider`, which is a function that lets you create a custom notification builder which should serve your needs.

```c#
...
FirebaseCloudMessagingImplementation.NotificationBuilderProvider = CreateCustomNotificationBuilder;
...

private NotificationCompat.Builder CreateCustomNotificationBuilder(FCMNotification notification)
{
    return new NotificationCompat.Builder(this, FirebaseCloudMessagingImplementation.ChannelId)
        .SetSmallIcon(Android.Resource.Drawable.SymDefAppIcon)
        .SetContentTitle("Custom notification")
        .SetContentText(notification.Body);
}


```
