### ISSUE TITLE
How do I intercept the push notification click and do something with it in the app

### ISSUE THREAD

**Issue by SteveSitekitcare** [TobiasBuchholz/Plugin.Firebase#213]
Hey all,

I've using firebase push notifications in my sample app. Its working well, my problem is I cant seem to do anything usefull with the click of the notification. 
What I want to do is identify the message type e.g What topic it was sent on so I can direct to the correct page in my app.
It looks like mainactivity.cs method "protected override void OnNewIntent(Intent intent)" is hit when the notication is tapped. but the intent object doesnt seem to contain anything of use?

IOS seems to use the following https://github.com/xamarin/GoogleApisForiOSComponents/blob/main/docs/Firebase/CloudMessaging/GettingStarted.md#handle-messages-received-through-the-fcm-apns-interface

which I havent even got round to

Can anyone help me.

**Comment by TobiasBuchholz** [comment]
Hi,
to handle a tapped notification you can use the [`IFirebaseCloudMessaging.NotificationTapped`](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/c01c20602aa5282d3be0204a4ae09c4c3d4c515c/src/CloudMessaging/Shared/IFirebaseCloudMessaging.cs#L62) event handler. It triggers an event that contains an instance of [`FCMNotification`](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/c01c20602aa5282d3be0204a4ae09c4c3d4c515c/src/CloudMessaging/Shared/FCMNotification.cs#L3), which should have all the information you need. Take a look at this [comment](https://github.com/TobiasBuchholz/Plugin.Firebase/issues/196#issuecomment-1694655561) that showcases the use of the `FCMNotiifcation.Data` property. 

If there are further questions don't hesitate to ask :)

**Comment by SteveSitekitcare** [comment]
> Hi, to handle a tapped notification you can use the [`IFirebaseCloudMessaging.NotificationTapped`](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/c01c20602aa5282d3be0204a4ae09c4c3d4c515c/src/CloudMessaging/Shared/IFirebaseCloudMessaging.cs#L62) event handler. It triggers an event that contains an instance of [`FCMNotification`](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/c01c20602aa5282d3be0204a4ae09c4c3d4c515c/src/CloudMessaging/Shared/FCMNotification.cs#L3), which should have all the information you need. Take a look at this [comment](https://github.com/TobiasBuchholz/Plugin.Firebase/issues/196#issuecomment-1694655561) that showcases the use of the `FCMNotiifcation.Data` property.
> 
> If there are further questions don't hesitate to ask :)

Thanks for the help @TobiasBuchholz I used this in the end
https://apoorv487.medium.com/testing-fcm-push-notification-through-postman-terminal-part-1-5c2df94e6c8d

**Comment by SteveSitekitcare** [comment]
closed
