### ISSUE TITLE
Firebase notifications not working on IOS

### ISSUE THREAD

**Issue by SteveSitekitcare** [TobiasBuchholz/Plugin.Firebase#223]
Hey

I have a working sample for android but the same sample wont work for IOS.
Its a dotnet 7 app.

I have followed this guide, with a few modifications from the main documentation in this repo.
https://cedricgabrang.medium.com/firebase-push-notifications-in-net-maui-ios-2f4388bf1ac

My sample can be found here
https://github.com/SteveSitekitcare/Samples/tree/firebase-notifications-dotnet7

Simply add the plist file from firebase and make sure the certificates are setup correctly

I used postman to push notifications which were succesfull for android but fail for IOS with the following error "InvalidRegistration" or "NotRegistered"
![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/138577988/ea85b450-96ad-42f3-ba57-8f4ab30cd821)
![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/138577988/d170b3c6-543a-4302-9ad8-d3a252bf6ede)

Things to note:

- I'm using a windows 10 pc as windows 11 has a max file path issue. 
- I connect remotely to a mac and use a virtual device to test.
- I have run the app without debug,
- I get a key when registering with firebase in the IOS app
- I get prompted in IOS for permission to use notifications 
- All keys and certificates seem to be working and I've installed the sandbox key within firebase
- I have tried using the messaging feature within the firebase web interface to send messages
- POSTMAN was setup using this guide https://www.youtube.com/watch?v=rQzexLu0eLU

Can someone help. ive been at this for weeks

Cheers
Steve

**Comment by LawrenceWlt** [comment]
I have been struggling for weeks too with the same issue. It works fine for Android but not on iOS. I have tried on a physical device and even pushed to TestFlight, none work.

**Comment by LawrenceWlt** [comment]
I even used WillFinishLaunching, it didn't work either.

**Comment by SteveSitekitcare** [comment]
> I even used WillFinishLaunching, it didn't work either.

I tried this too. I'm currently trying shiny.net https://github.com/shinyorg/shiny

**Comment by LawrenceWlt** [comment]
@SteveSitekitcare did you manage to make push notifications work with shiny.net? I have tried it but am not getting FCM token.

**Comment by TobiasBuchholz** [comment]
Hi @SteveSitekitcare,
I have taken a look at your sample project and identified two issues that might be the reason for your app to not receive any push notifications:

1. Your `MauiApp1/Platforms/iOS/Entitlements.plist` file contains entries that don't belong there but in the `Info.plist`. I guess you made a simple copy-paste mistake? The most minimalistic `Entitlements.plist` that supports push notifications looks like the following:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
</dict>
</plist>
```

2. Why does your MauiApp1.csproj file contain `PropertyGroup` entries like the following:

```xml
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0-ios|AnyCPU'">
  <ApplicationTitle>FirebaseNotifications</ApplicationTitle>
  <ApplicationId>uk.co.sitekitcare.firebasenotifications</ApplicationId>
</PropertyGroup>
```

The specified `ApplicationId` (uk.co.sitekitcare.firebasenotifications) doesn't match the one specified at the one in the topmost `PropertyGroup` (com.companyname.mauiapp1). Either use the same application id in all the `ApplicationId` entries or just delete the above stated `PropertyGroup` items alltogether and make sure you use the same application id as specified in the `GoogleService-Info.plist`.

-----------

After applying those changes I was able to receive push notifications on my physical device with your sample app by using the following curl command:

```
curl --location 'https://fcm.googleapis.com/fcm/send' \
--header 'Authorization: key=<your-api-token-from-firebase-console-cloud-messaging-project-settings>' \
--header 'Content-Type: application/json' \
--data '{
 "to" : "<your-device-fcm-token>",
 "collapse_key" : "type_a",
 "mutable_content": true,
 "notification" : {
     "body" : "body of token notification",
      "title": "title of token notification",
     "badge": 1
 },
 "data" : {
     "body" : "Body of Your Notification in Data",
     "title": "Title of Your Notification in Data"
 }
}'
```

As a last hint: after reinstalling the app the fcm token might change which causes the 'NotRegistered' response, so make sure to press your "Click me" button a few times to really have the current fcm token. Furthermore you can also take a look at the [sample project](https://github.com/andyzukunft/Plugin.Firebase/tree/fcm-demo) created by @andyzukunft.

I hope this helps!

**Comment by SteveSitekitcare** [comment]
> Hi @SteveSitekitcare, I have taken a look at your sample project and identified two issues that might be the reason for your app to not receive any push notifications:
> 
> 1. Your `MauiApp1/Platforms/iOS/Entitlements.plist` file contains entries that don't belong there but in the `Info.plist`. I guess you made a simple copy-paste mistake? The most minimalistic `Entitlements.plist` that supports push notifications looks like the following:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
> <plist version="1.0">
> <dict>
> 	<key>aps-environment</key>
> 	<string>development</string>
> </dict>
> </plist>
> ```
> 
> 2. Why does your MauiApp1.csproj file contain `PropertyGroup` entries like the following:
> 
> ```
> <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0-ios|AnyCPU'">
>   <ApplicationTitle>FirebaseNotifications</ApplicationTitle>
>   <ApplicationId>uk.co.sitekitcare.firebasenotifications</ApplicationId>
> </PropertyGroup>
> ```
> 
> The specified `ApplicationId` (uk.co.sitekitcare.firebasenotifications) doesn't match the one specified at the one in the topmost `PropertyGroup` (com.companyname.mauiapp1). Either use the same application id in all the `ApplicationId` entries or just delete the above stated `PropertyGroup` items alltogether and make sure you use the same application id as specified in the `GoogleService-Info.plist`.
> 
> After applying those changes I was able to receive push notifications on my physical device with your sample app by using the following curl command:
> 
> ```
> curl --location 'https://fcm.googleapis.com/fcm/send' \
> --header 'Authorization: key=<your-api-token-from-firebase-console-cloud-messaging-project-settings>' \
> --header 'Content-Type: application/json' \
> --data '{
>  "to" : "<your-device-fcm-token>",
>  "collapse_key" : "type_a",
>  "mutable_content": true,
>  "notification" : {
>      "body" : "body of token notification",
>       "title": "title of token notification",
>      "badge": 1
>  },
>  "data" : {
>      "body" : "Body of Your Notification in Data",
>      "title": "Title of Your Notification in Data"
>  }
> }'
> ```
> 
> As a last hint: after reinstalling the app the fcm token might change which causes the 'NotRegistered' response, so make sure to press your "Click me" button a few times to really have the current fcm token. Furthermore you can also take a look at the [sample project](https://github.com/andyzukunft/Plugin.Firebase/tree/fcm-demo) created by @andyzukunft.
> 
> I hope this helps!

Ahh thats pretty embarrassing, my app now pushes to the mobile but I'm getting the following 

`2023-11-02 12:17:45.257 Xamarin.PreBuilt.iOS[767:166000] Could not resolve assembly Microsoft.VisualStudio.DesignTools.TapContract, Version=17.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/8397066B-0CD3-4CAA-8FF8-F52494648DE3/Documents/MauiApp3.content/Microsoft.VisualStudio.DesignTools.TapContract.dll' or one of its dependencies.

2023-11-02 12:17:45.255 Xamarin.PreBuilt.iOS[767:166000] Could not resolve assembly Xamarin.HotReload.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/8397066B-0CD3-4CAA-8FF8-F52494648DE3/Documents/MauiApp3.content/Xamarin.HotReload.Contracts.dll' or one of its dependencies.

Thread started:  #9
2023-11-02 12:17:45.674 Xamarin.PreBuilt.iOS[767:166000] Could not resolve assembly System.Private.DataContractSerialization.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/8397066B-0CD3-4CAA-8FF8-F52494648DE3/Documents/MauiApp3.content/System.Private.DataContractSerialization.resources.dll' or one of its dependencies.

Thread started:  #10
Thread started:  #11
2023-11-02 12:17:45.673 Xamarin.PreBuilt.iOS[767:166000] Could not resolve assembly System.Private.DataContractSerialization.resources, Version=7.0.0.0, Culture=en-GB, PublicKeyToken=null. Details: Could not load file or assembly '/var/mobile/Containers/Data/Application/8397066B-0CD3-4CAA-8FF8-F52494648DE3/Documents/MauiApp3.content/System.Private.DataContractSerialization.resources.dll' or one of its dependencies.

[0:] An error occurred: 'Object reference not set to an instance of an object.'. Callstack: '   at Plugin.Firebase.CloudMessaging.FirebaseCloudMessagingImplementation.RegisterForRemoteNotifications()
   at Plugin.Firebase.CloudMessaging.FirebaseCloudMessagingImplementation.Initialize()
   at Plugin.Firebase.Bundled.Platforms.iOS.CrossFirebase.Initialize(CrossFirebaseSettings settings, Options firebaseOptions, String name)
   at MauiApp1.MauiProgram.<>c.<RegisterFirebaseServices>b__1_4(UIApplication app, NSDictionary launchOptions) in C:\Git\Sandbox\MauiApp1\MauiProgram.cs:line 46
   at Microsoft.Maui.MauiUIApplicationDelegate.<>c__DisplayClass6_0.<FinishedLaunching>b__1(FinishedLaunching del)
   at Microsoft.Maui.LifecycleEvents.LifecycleEventServiceExtensions.InvokeLifecycleEvents[FinishedLaunching](IServiceProvider services, Action`1 action)
   at Microsoft.Maui.MauiUIApplicationDelegate.FinishedLaunching(UIApplication application, NSDictionary launchOptions)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at MauiApp1.Program.Main(String[] args) in C:\Git\Sandbox\MauiApp1\Platforms\iOS\Program.cs:line 13
   at System.Reflection.MethodInvoker.InterpretedInvoke(Object obj, Span`1 args, BindingFlags invokeAttr)'
The app has been terminated.`

Did a quick search and I think its a Visual Studio Issue

https://github.com/dotnet/maui/issues/17189
https://github.com/dotnet/maui/issues/14844

**Comment by LawrenceWlt** [comment]
I was able to make it work by enabling Cloud Messaging Legacy API on the Firebase console which will expire on 20th June 2024. Is there a plan to migrate to Firebase Cloud Messaging API (V1)?

**Comment by SteveSitekitcare** [comment]
Hey @TobiasBuchholz 
Do you have any instructions on setting up the IOS provision profile?

Still struggling with this and its going to be a show stopper for my project if I can get push notifications working.

Cheers

**Comment by TobiasBuchholz** [comment]
Hi @SteveSitekitcare,

1. No, I don't have any instructions on setting up the iOS provisioning profile, because there are plenty tutorials available on the web already, like [Push Notifications in iOS](https://learn.microsoft.com/en-us/xamarin/ios/platform/user-notifications/deprecated/remote-notifications-in-ios) from Microsoft or [this video](https://www.youtube.com/watch?v=GNBuaAB8nR8) by [Gerald Versluis](https://www.youtube.com/@jfversluis).

2. For testing push notifications I'm using a real iPad Pro 11 device and deploy my apps directly onto it, which works fine, also in debug mode, so nothing special here either.

Hope this helps :)

**Comment by SteveSitekitcare** [comment]
> Hi @SteveSitekitcare,
> 
> 1. No, I don't have any instructions on setting up the iOS provisioning profile, because there are plenty tutorials available on the web already, like [Push Notifications in iOS](https://learn.microsoft.com/en-us/xamarin/ios/platform/user-notifications/deprecated/remote-notifications-in-ios) from Microsoft or [this video](https://www.youtube.com/watch?v=GNBuaAB8nR8) by [Gerald Versluis](https://www.youtube.com/@jfversluis).
> 2. For testing push notifications I'm using a real iPad Pro 11 device and deploy my apps directly onto it, which works fine, also in debug mode, so nothing special here either.
> 
> Hope this helps :)

Appreciate the help, 1 last question (hopefully)
What OS do you use to develop on e.g. windows 11, MacOS?

**Comment by TobiasBuchholz** [comment]
Sure, I'm developing on MacOS with an Apple M1 Pro Chip

**Comment by SteveSitekitcare** [comment]
> Sure, I'm developing on MacOS with an Apple M1 Pro Chip

From trying for a month, there seems to be for too many issues with Windows (specifically windows 11) and everyone who has this working who I have spoke to seems to using a mac.

My issues all seem to be related to file path length, which mac doesnt suffer from. 

Ive requested a Mac, I'll feedback here on my results.


Thankyou for the help
