### ISSUE TITLE
MAUI: NotificationTapped event is not firing in foreground mode

### ISSUE THREAD

**Issue by sreejith-pagematics** [TobiasBuchholz/Plugin.Firebase#226]
I am using `Plugin.Firebase` and `Plugin.Firebase.Crashlytics` packages for implementing push notification in my MAUI application. I referred [this](https://cedricgabrang.medium.com/firebase-push-notifications-in-net-maui-android-32c808844d7e) blog and it was working fine on the Android platform.

I have added the `NotificationTapped` event on the `App.xaml.cs` Constructor. This event is firing when the app is in `Background` or `Killed` modes. But the app is in foreground mode, this event is not firing. Below is my code:

	public partial class App : Application
	{
		public App()
		{
			InitializeComponent();
			CrossFirebaseCloudMessaging.Current.NotificationTapped += Current_NotificationTapped;
		}

		private void Current_NotificationTapped(object sender, FCMNotificationTappedEventArgs e)
		{
			try
			{
				var data = e.Notification.Data;
				//reading data from notiifcatin and opening the page
			}
			catch (Exception ex)
			{
				System.Diagnostics.Debug.WriteLine("Exception:>>" + ex);
			}
		}
	}

Is anything else we need to do for firing this event on foreground mode?

**Comment by TobiasBuchholz** [comment]
The `NotificationTapped` event is supposed to be firing when tapping the notification regardless in which mode the app is. Are you calling the `FirebaseCloudMessagingImplementation.OnNewIntent(intent)` method in the `OnCreate` and `OnNewIntent` methods of your `MainActivity` class? 

You can take a look at the samples `MainActivity` as reference: https://github.com/TobiasBuchholz/Plugin.Firebase/blob/b6ccded2d442f38d29ac74ae3307dcc1d70d0c1b/sample/Playground/Platforms/Android/MainActivity.cs#L24

**Comment by sreejith-pagematics** [comment]
@TobiasBuchholz 
I didn't add the `OnNewIntent` method on MainActivity class. Now I added that and foreground notification tapping is working fine.

**Comment by sreejith-pagematics** [comment]
@TobiasBuchholz Is this package support for iOS?
