### ISSUE TITLE
Question about Windows Support

### ISSUE THREAD

**Issue by e012345678** [TobiasBuchholz/Plugin.Firebase#230]
I know that there is currently no Windows (WNS) support. But is it planned and is it possible? I think I read somewhere its not possible for some reason but can't find it now.

**Comment by TobiasBuchholz** [comment]
Firebase only supports android, iOS, web, unity and flutter apps, so unfortunately no windows. See https://github.com/TobiasBuchholz/Plugin.Firebase/issues/73 if you still want to include the plugin into your Forms/Maui application without working push notifications on windows.
