### ISSUE TITLE
MSB3023 Error while building on net8 ios

### ISSUE THREAD

**Issue by Asmoyed** [TobiasBuchholz/Plugin.Firebase#237]
Hello on my MAUI project I'm unable to build for ios net8.

Visual studio is unable to copy the files from the .nuget folder into the project with the MSB3026 error :

```
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4911,5): warning MSB3026: Impossible de copier "C:\Users\touta\.nuget\packages\xamarin.firebase.ios.cloudmessaging\8.10.0.3\lib\net6.0-ios15.4\Firebase.CloudMessaging.resources\FirebaseMessaging.xcframework\ios-arm64_x86_64-simulator\FirebaseMessaging.framework\Headers\FIRMessagingExtensionHelper.h" vers "bin\Debug\net8.0-ios\iossimulator-x64\Firebase.CloudMessaging.resources\FirebaseMessaging.xcframework\ios-arm64_x86_64-simulator\FirebaseMessaging.framework\Headers\FIRMessagingExtensionHelper.h". Nouvelle tentative de l'opération 8 dans 1000 ms. Impossible de trouver une partie du chemin d'accès 'bin\Debug\net8.0-ios\iossimulator-x64\Firebase.CloudMessaging.resources\FirebaseMessaging.xcframework\ios-arm64_x86_64-simulator\FirebaseMessaging.framework\Headers\FIRMessagingExtensionHelper.h'.
```

It says it can't find the files but manually i can see them using file explorer.

I thought it was due to the length of the path that is more than 260 caracters long, i've tried enabling the long path registry key but it did not change anything.

Any help is appreaciated thanks

**Comment by Gius95** [comment]
I solved it with theese 2 steps:
- Change the Nuget folder to be in a shortened path (like C:\Nuget). You can follow this tutorial: [https://stackoverflow.com/a/76028284](https://stackoverflow.com/a/76028284)
- Change the project folder too to be shorten. Try to putting directly under C:\ like C:\YourProject

**Comment by Asmoyed** [comment]
Thank you very much, for your answer it worked for me also.
Closing my issue as it's working
