### ISSUE TITLE
[Feature] Enable Firebase emulators

### ISSUE THREAD

**Issue by Kapusch** [TobiasBuchholz/Plugin.Firebase#24]
Hello @TobiasBuchholz ,

I wonder if this is currently possible to enable Firebase emulators with your library ?

As your library provides a wrapper for all Firebase services, it would be very good being able to activate the Firebase emulators instead of pointing to an actual Firebase instance.

Is it something you already planned to add ? Do you have an idea about the required implementation ?
I would like to help on that but I do not have yet knowledge on how to do it.

**Comment by TobiasBuchholz** [comment]
Sounds like a good idea, I will take a look into it.

**Comment by TobiasBuchholz** [comment]
Good news! The library will be able to support the usage of the firebase emulator suite. I've added the `UseEmulator(host, port)` wrapper methods at all supporting services and added a [new section](https://github.com/TobiasBuchholz/Plugin.Firebase#using-firebase-local-emulator-suite) to the project's README file for more information.

**Comment by Kapusch** [comment]
Awesome, thank you !

**Comment by Kapusch** [comment]
Hi @TobiasBuchholz , I did want to try it out, but actually I'm not able to call **UseEmulator** from any of your exposed services (Auth, Firestore, Storage, ...)

`'IFirebaseFirestore' does not contain a definition for 'UseEmulator' and no accessible extension method 'UseEmulator' accepting a first argument of type 'IFirebaseFirestore' could be found (are you missing a using directive or an assembly reference?)`
<img width="903" alt="image" src="https://user-images.githubusercontent.com/9576733/181995789-d895ba21-bcfd-482f-8dbc-bed0fb14bf07.png">

I am referencing your last package (1.1.2) in my app, and I already cleaned the solution + clear NuGet packages cache.
Could you please try referencing your package and see if you're able to call UseEmulator ?
