### ISSUE TITLE
Crashlytics not initialize with MAUI .NET 8 

### ISSUE THREAD

**Issue by Ankit8913** [TobiasBuchholz/Plugin.Firebase#241]
I've recently upgraded my maui project to .NET8 where Crashlytics was not working after upgrading to .NET 8.

When I run the project I am getting following errors:

[I-CLS000000] Crashlytics could not find the symbol for the app's main function and cannot start up. This can happen when Exported Symbols File is set in Build Settings. To resolve this, add "__mh_execute_header" as a newline to your Exported Symbols File.

[I-CLS000000] Crash reporting could not be initialized

Any idea on what might be the issue ?

**Comment by ultimategrandson** [comment]
I am having this same problem. I don't use this plugin library, the issue seems to be the actual Xamarin.Firebase.iOS.Crashlytics - I have not been able to find a solution as of yet.

**Comment by rjhind** [comment]
I use the Xamarin.Firebase.iOS.Crashlytics package and also have the issue where crashlytics doesn't report anything so I'm guessing it the same.

**Comment by popandov** [comment]
Can anyone update on this one ? I can't seem to get iOS crashlytics to work on net8.0.
@Ankit8913  maybe you found something ?

**Comment by ultimategrandson** [comment]
This work around seems to work: https://github.com/xamarin/GoogleApisForiOSComponents/issues/643#issuecomment-1921067013

**Comment by AdamEssenmacher** [comment]
DSYMs only being uploaded on Release builds has nothing to do with the `_ExportSymbolsExplicitly` workaround. It's a configurable setting: https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/tree/main/source/Firebase/Crashlytics
