### ISSUE TITLE
Crashlytics exception stacktrace

### ISSUE THREAD

**Issue by tranb3r** [TobiasBuchholz/Plugin.Firebase#243]
Hi,

I've just realized that Crashlytics in not showing the stacktrace of recorded exceptions.

Here is the StackTraceParser regex in the current version:
`^\s*at (?<className>\S+)\.(?<methodName>\S+ \(.*\)) (?<offset>.*?)( in (?<fileName>.+):(?<lineNumber>\d+))?\s*$`

I think the correct regex should be:
`^\s*at (?<className>\S+)\.(?<methodName>\S+\(.*\))( in (?<fileName>.+):line (?<lineNumber>\d+))?\s*$`

Tested with this trace:
`   at MyNamespace.MyClass.MyMethod(MyParameters) in C:\MyFolder\MyFile.cs:line 42`

Result:
- className: MyNamespace.MyClass
- methodName: MyMethod(MyParameters)
- fileName: C:\MyFolder\MyFile.cs
- lineNumber: 42

What do you think?

**Comment by TobiasBuchholz** [comment]
Hey @tranb3r, sorry for the late response and thanks a lot for your contribution! The fix is now released with Plugin.Firebase.Crashlytics 2.0.2 and Plugin.Firebase 2.0.10 🚀
