### ISSUE TITLE
Issue with crashlytics initialization

### ISSUE THREAD

**Issue by Murtuzakabul** [TobiasBuchholz/Plugin.Firebase#248]
I configured the plugin as per instructions. However I'm getting this error while trying to run my application

![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/17959034/e3365f7e-1e2a-4452-a3f4-a94d8f31f476)

I made sure that the google-service.json file is there in my project along with respective info.plist file too. 

Not able to understand what is causing the issue. Please let me know what further information is needed to fix this issue.

Here is the code of my mauiprogram.cs

```    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();


            builder
                .UseMauiApp<App>()
                .UseMauiCommunityToolkit()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                    fonts.AddFont("OpenSans-Semibold.ttf", "OpenSansSemibold");
                })
                 .ConfigureDeviceIdProvider()
                 .RegisterFirebaseServices();
                 
                

            builder.Services.AddSingleton<DataService, DataService>(s =>
            {
                return new DataService(new JsonSerializerOptions()
                {
                    WriteIndented = true,
                    PropertyNamingPolicy = null,
                    PropertyNameCaseInsensitive = false,
                });
            });
            

#if DEBUG
            builder.Logging.AddDebug();
#endif

            return builder.Build();
        }


        private static MauiAppBuilder RegisterFirebaseServices(this MauiAppBuilder builder)
        {

            builder.ConfigureLifecycleEvents(events => {
#if IOS
                events.AddiOS(iOS => iOS.WillFinishLaunching((_, __) => {
                    CrossFirebase.Initialize();
                    return false;
                }));
#elif ANDROID
                events.AddAndroid(android => android.OnCreate((activity, _) => {
                }));
                
#endif
            });


            builder.Services.AddSingleton(_ => CrossFirebaseAuth.Current);
            return builder;
        }



    }

**Comment by tranb3r** [comment]
In the doc:
https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/docs/crashlytics.md#android-specifics

**Comment by tranb3r** [comment]
Most probably you forgot to set `mapping_file_id`?
https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/docs/crashlytics.md#android-specifics

**Comment by Murtuzakabul** [comment]
> Most probably you forgot to set `mapping_file_id`? https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/docs/crashlytics.md#android-specifics

I've added it. Attaching here a screenshot of the same so as to ensure that it has been added correctly..

![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/17959034/7048c352-8bd7-4174-81d2-d84df8f72866)

**Comment by tranb3r** [comment]
The folder should be `Platforms/Android/Resources/values`

**Comment by Murtuzakabul** [comment]
> The folder should be `Platforms/Android/Resources/values`

I'm trying the same and will let you know.

**Comment by Murtuzakabul** [comment]
Worked!!. Can you please guide me on what documentation should I follow to enable push notification. Thanks a lot.

**Comment by tranb3r** [comment]
For push notification, here is the link to the documentation:
https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/docs/cloud_messaging.md
You should probably also have a look at the sample's code.
