### ISSUE TITLE
Firestore: nullable long property not bound on iOS

### ISSUE THREAD

**Issue by SeriousM** [TobiasBuchholz/Plugin.Firebase#249]
Given is

* a property on a class what we'll map onto a firestore document.

```cs
[FirestoreData]
public class UserModel
{
  [FirestoreProperty("userId")]
  public long? UserId { get; set; }
}
```

* the firestore document itself

version 1:
```
userId (number) = 123
```
or

version 2:
```
userId (null) = null
```

On Android the version 1 and 2 is binding very well onto the model, on iOS neither on version 1 or 2 a value is bound at all.
When I change the property from `long? UserId` to `long UserId` the value is bound well.

I suspect that the NSObject-netObect mapping is a problem here and I guess there is no way to fix that, right?

Thank you very much for all your work!!

**Comment by TobiasBuchholz** [comment]
The PR #250 is contained in Plugin.Firestore 2.0.11 and Plugin.Firebase.Firestore 2.0.6 🚀
