### ISSUE TITLE
[Feature] Raise specific exceptions for common errors on all Firebase services

### ISSUE THREAD

**Issue by Kapusch** [TobiasBuchholz/Plugin.Firebase#25]
Hello @TobiasBuchholz ,

I wonder about how to catch specific auth exceptions, such as : 
- Wrong password,
- Unverified email,
- User not found,
- Session expired...

Actually, I would like being able to display the right message to the user according to the internal encountered error, whether it's related to Authentication or Firestore, Storage...
Is it possible with the current implementation ?

If no, could we plan about grouping common errors related to all Firebase services please ?

**Comment by TobiasBuchholz** [comment]
Hi @Kapusch  

this probably makes sense so I will take a look into it. If you have any further suggestions on how to implement that you are welcome to share them here.
