### ISSUE TITLE
.NET MAUI support and ApplicationId 

### ISSUE THREAD

**Issue by lomdar67** [TobiasBuchholz/Plugin.Firebase#253]
Not really an issue, more a question:

In the .Net Maui part of the documentation it states:

Ensure the **ApplicationId** in your .csproj file matches the **bundle_id** and **package_name** inside of the [GoogleService-Info.plist|google-services.json] files.

What is the solution if you have a old app where bundle_id and package_name are not identical?

Thanks for your help,
Michael

**Comment by TobiasBuchholz** [comment]
Hi Michael, generally speaking it's no problem if the bundle_id for the iOS app differs from the the package_name for the android app. In that case you can't use the ApplicationId attribute in the .csproj file but need to enter it in the `Info.plist` and `AndroidManifest.xml` files separately.

- iOS: **bundle_id** needs to be the same as in `Info.plist` and `GoogleService-Info.plist`
- android: **package_name** needs to be the same as in `AndroidManifest.xml ` and `google-services.json`

Hope this helps! :)

**Comment by lomdar67** [comment]
Hello Tobias,

thanks for your help. I'm using Cloud Messaging with an app we have for iOS and Android. In Android everything works fine, I get a token and can receive messages. In iOS I get a FirebaseException:

Plugin.Firebase.Core.Exceptions.FirebaseException
  Message=Couldn't retrieve FCM token
  Source=Plugin.Firebase.CloudMessaging

Don't know where exactly the problem is an how to debug it so I thought maybe it has something to do with the ApplicationId.
But the bunde_id in Info-plist and the one in  GoogleService-Info.plist are matching so the problem must be somwhere else...
