### ISSUE TITLE
Crashlytics exception stacktrace

### ISSUE THREAD

**Issue by tranb3r** [TobiasBuchholz/Plugin.Firebase#254]
Hi,

I think Crashlytics is still not showing the full stacktrace of recorded exceptions.

Here is the StackTraceParser regex in the current version:
`^\s*at (?<className>\S+)\.(?<methodName>\S+\(.*\))( in (?<fileName>.+):line (?<lineNumber>\d+))?\s*$`

If you test it with this trace line:
```at System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].FindValue(String key) in C:\MyFolder\MyFile.cs:line 42```

The regex has no match (because of spaces in the full class name). As a consequence, the trace line is ignored by Plugin.Firebase, so it does not appear in crashlytics, which is a problem.

I think the correct regex should be:
`^\s*at (?<className>.+)\.(?<methodName>.+\(.*\))( in (?<fileName>.+):line (?<lineNumber>\d+))?\s*$`

Result:
```
className: System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
methodName: FindValue(String key)
fileName: C:\MyFolder\MyFile.cs
lineNumber: 42
```

What do you think?
I can prepare a PR if you want.
Thanks.

**Comment by TobiasBuchholz** [comment]
Hi @tranb3r,
yeah seems about right, so go for it and thanks! :)

**Comment by tranb3r** [comment]
Thank you!
