### ISSUE TITLE
Coverting from IDocumentSnapshot<T> to a List<T>

### ISSUE THREAD

**Issue by rezamohamed** [TobiasBuchholz/Plugin.Firebase#256]
This is more a usage question Plugin.Firebase.Firestore.

I can retreieve an IEnumberable<IDocumentSnapshot<T>> using 

            var snapshot = await CrossFirebaseFirestore
                .Current
                .GetCollection("NewCollection")
                .GetDocumentsAsync<Pokemon>();

            var docs = snapshot.Documents;

But to create a List<Pokemon> is the only way to iterate through snapshot.documents like so?

            List<Pokemon> allData = new List<Pokemon>();
            
            foreach (var doc in snapshot.Documents)
            {
                allData.Add(doc.Data);
            }

I've used this plugin in Xamarin before, https://github.com/f-miyu/Plugin.CloudFirestore/tree/master?tab=readme-ov-file#get and it does a direct ToObject, so didn't know if I was missing something here is all.

**Comment by AdamEssenmacher** [comment]
The `Documents` property is an `IEnumerable<T>` for good reason. It defers the work needed to translate underlying native data objects to cross-platform .NET objects.

You can use the standard .NET extension method `.ToList()` to transform the `IEnumerable<T>` into a `List<T>`. This is functionally equivalent to the code you've posted but more terse.

**Comment by rezamohamed** [comment]
My issue isn't with the IEnumerable<T>, performing a ToList like so simply gives me a List instead of the IEnumberable.

var docs = snapshot.Documents.ToList();

My question was that I still have a List<IDocumentSnapshot>, I am looking to get the List<Pokemon> without having to iterate through and add each Pokemon to the list.

**Comment by AdamEssenmacher** [comment]
Ah sorry. I understand now. The `ToObjects()` and `ToObject()` methods in the other plugin are just convenience methods for iterating over each snapshot just like you're doing. This plugin doesn't have equivalents right now, so yes you'll need to iterate yourself like: `snapshot.Documents.Select(d => d.Data)`. It would be an easy enough thing to add, or create an extension method for.

**Comment by rezamohamed** [comment]
Thanks @AdamEssenmacher that was my hunch, but i wanted to just make sure. The sample project here doesn't have a sample for firestore, so wanted to make sure I wasn't missing something
