### ISSUE TITLE
Unhandled Exception on iOS implementation of RunTransactionAsync

### ISSUE THREAD

**Issue by Kapusch** [TobiasBuchholz/Plugin.Firebase#26]
Hi @TobiasBuchholz ,

Just to let you know that exceptions cannot be handled if they occur in the iOS implementation for RunTransactionAsync :
https://github.com/TobiasBuchholz/Plugin.Firebase/blob/68f577fd8f09180ebeeaee24b4ccf92a632918e0/src/iOS/Firestore/FirebaseFirestoreImplementation.cs#L31
<img width="912" alt="image" src="https://user-images.githubusercontent.com/9576733/158079334-ddd5425f-5f7c-4eec-b3ea-f30a5fec67d4.png">

This is annoying as the app is crashing even in a try catch block.
I have tried to fix it but with no success so far... Would you know how to fix it ?

Thanks in advance

**Comment by TobiasBuchholz** [comment]
Hi @Kapusch,

this is indeed a problem and needs to be fixed. I can see no way how the calling code should be able to prevent the exception at this point. I've made a [fix](https://github.com/TobiasBuchholz/Plugin.Firebase/commit/951fe6d6fb0f722d788031ca450037ff84738a04#diff-f3365ab00185a17a4f65b439463a4b3972783f6979f44431e8404868c910829b) so this shouldn't happen in the upcoming versions of the library anymore.

**Comment by Kapusch** [comment]
Thanks Tobias, willing to test this soon !
