### ISSUE TITLE
No way to query where in?? 

### ISSUE THREAD

**Issue by robertmaxted** [TobiasBuchholz/Plugin.Firebase#260]
try
                {
                    var businessesInfoQuery = await CrossCloudFirestore.Current.Instance
                                                                       .Collection("businesses")
                                                                       .WhereIn(FieldPath.DocumentId, someListOfStrings)
                                                                       .GetAsync();
                                                                       
                                                                       
This is what I was previously using in Plugin.CloudFirestore (by f-miyu) in Xamarin.forms. Seems the only way using this Plugin.Firebase.Firestore is to get all documents and filter on the client?? This is not an option (could be 10k documents)..? Please advise? 

@TobiasBuchholz @vhugogarcia @Gekidoku @AdamEssenmacher

**Comment by AdamEssenmacher** [comment]
The method is named `WhereFieldIn`.

Just like the other plugin, Plugin.Firebase is mostly just a .NET wrapper around the native Objective-C and Java binding libraries, which are, in turn, bridges to the native SDKs. The naming conventions between each native SDK can be slightly different, so when we're picking a unified name for this plugin we just kinda have to 'pick one'.

**Comment by robertmaxted** [comment]
Hi @AdamEssenmacher Thanks for such a quick reply. I have managed to get it working (well.. No red lines haha). Had to create the ToObject<> (extensions) implementations also. Is there a likelihood that they will be created anytime soon? Also I appreciate this must have been a challenge (supporting .NET MAUI)! So many thanks.
