### ISSUE TITLE
[QUESTION] Problem parsing enums - Firestore

### ISSUE THREAD

**Issue by hergarcia** [TobiasBuchholz/Plugin.Firebase#261]
Hello, I have this question that I am not being able to finde an answer and is blocking me to develop my App in MAUI.

I am receiving **"Object of type 'System.Int64' cannot be converted to type 'MyEnum'."**
Is there a way to keep using the Enums directly in my model or have to refactor all and do the int way?

Thanks in advance!

**Comment by hergarcia** [comment]
I just found the solution.

`public class MyEnum : long { }`

I hope this helps somebody and sorry for the silly question.

**Comment by mihaimyh** [comment]
It doesnt work, or I am doing something wrong:

![Image](https://github.com/user-attachments/assets/faf5ad94-1dbe-4726-b0d2-06b716fed045)
