### ISSUE TITLE
Updating an array..

### ISSUE THREAD

**Issue by robertmaxted** [TobiasBuchholz/Plugin.Firebase#265]
Hi Guys, @TobiasBuchholz @vhugogarcia @Gekidoku @AdamEssenmacher 

I am trying to update an array of maps but I am getting an error similar to this:

Message	"Do not know how to marshal object of type 'System.Collections.Generic.List`1[NameSpace.SomeModel]' to an NSObject"	

here is an example Model (to simplify what I am trying to do)..

```
public class SomeModel
    {
        [FirestoreDocumentId]
        [JsonIgnore]
        public string Id { get; set; }

        [FirestoreProperty("some_array")]
        [JsonProperty("some_array")]
        public List< MapModel > SomeArray { get; set; }
    }
    
    
    public class MapModel
    {
        [FirestoreProperty("some_uid_id")]
        [JsonProperty("some_uid_id")]
        public string SomeUid { get; set; }

        [FirestoreProperty("rating")]
        [JsonProperty("rating")]
        public double Rating { get; set; }

        [JsonIgnore]
        public int Position { get; set; }
    }
    
```

And here is what I am trying to do:

```
var path = $"some_collection/some_doc";
var someIDocReference = CrossFirebaseFirestore.Current.GetDocument(path);

someModel = someIDocReference.GetDocumentSnapshotAsync< SomeModel >().Result.Data;

var fieldsToUpdate = new Dictionary<object, object>
                                {
                                    { "some_array", someModel.SomeArray }
                                };

transaction.UpdateData(someIDocReference, fieldsToUpdate);
```

it is on this line where I get the error:

`transaction.UpdateData(someIDocReference, fieldsToUpdate);`

Any help would be greatly appreciated! 

Kind regards,
Rob.

**Comment by AdamEssenmacher** [comment]
Try using an IList instead of a List.

**Comment by robertmaxted** [comment]
Ahh.. I see.. But List doesn't have all of the methods ie sorting etc.. Is there no way it can be done with List<T> ? Thanks for the quick response Adam, I appreciate it.

**Comment by robertmaxted** [comment]
@AdamEssenmacher I am trying to run a transaction and update an array of maps within a document.. I must be going wrong here somewhere. 

`transaction.UpdateData(documentReference, ("some_array", tempList));`

Error:
Message	"Could not convert object of type NameSpace.Models.MapModel to NSObject. Does it extend IFirestoreObject?"

**Comment by AdamEssenmacher** [comment]
@robertmaxted have you figured it out yet? The error message is hinting that your models should extend IFirestoreObject, and it doesn't look like your models do...

**Comment by robertmaxted** [comment]
That worked a treat! Thanks Adam I really appreciate it!
