### ISSUE TITLE
Problem with old firebase cloud messaging binding project

### ISSUE THREAD

**Issue by kellertimo** [TobiasBuchholz/Plugin.Firebase#269]
As Plugin.Firebase also has a dependency to Xamarin.Firebase.iOS.CloudMessaging (according to Nuget) I have the following question:

Firebase notifications will not work anymore because it requires iOS SDK version >= 10 after 20.6.24

Any idea what to do here besides asking Microsoft to update the bindings?

There is also a discussion here: https://github.com/dotnet/maui/discussions/20359

**Comment by AdamEssenmacher** [comment]
I've been badgering Microsoft and the MAUI team for months on this issue. They simply don't respond.
