### ISSUE TITLE
GetFcmTokenAsync() hangs forever

### ISSUE THREAD

**Issue by mrnams** [TobiasBuchholz/Plugin.Firebase#278]
Hi, when I call GetFcmTokenAsync() programs hangs forever and never get fcm token

**Comment by TobiasBuchholz** [comment]
Hi, could you please provide a sample project that demonstrates this issue? Thanks!

**Comment by mrnams** [comment]
I tried to share minimal code with you, but unfortunately I could success, my project is big one and its hard for me to minimize it, and due to privacy reason cant share it complete, however I share steps to reproduce it.
GetFcmTokenAsync()  hangs forever when called in view models/Models and only works when called view (code behind) , so I get FCM token in view on button click and use it to save in database.
