### ISSUE TITLE
[Storage] IStorageReference is missing the GetBytes method

### ISSUE THREAD

**Issue by tranb3r** [TobiasBuchholz/Plugin.Firebase#279]
Hi,

It looks like `IStorageReference` (from Firebase Storage) is missing the `GetBytes` method.
It only has a `GetStream` method.
Is it possible to add the `GetBytes` method?

Thanks!

**Comment by TobiasBuchholz** [comment]
Hi @tranb3r,

I've just added the missing `GetBytes()` method and released it with Plugin.Firebase.Storage 2.0.3 or Plugin.Firesbase 2.0.13 🚀

**Comment by tranb3r** [comment]
@TobiasBuchholz 
Thanks a lot!
