### ISSUE TITLE
Need clarification

### ISSUE THREAD

**Issue by philm001** [TobiasBuchholz/Plugin.Firebase#288]
Hello everyone

Not really an issue per say but need some clarification. 

Just want to check if this package is compatible with .Net 8?

There are some steps that are referring to .Net 6 and I was wondering if I need to copy/paste those into my .Net 8 project or should I edit the example to work for .Net 8?

Please let me know

**Comment by AdamEssenmacher** [comment]
I haven't had any issues using the package as-is using .NET 8.

**Comment by philm001** [comment]
Hello Adam, thank you for letting me know. Using the tutorials, did you convert the things to .net 8 or stuck with the .net 6 references?

**Comment by AdamEssenmacher** [comment]
What 'things' are you referring to here?

**Comment by philm001** [comment]
This part in the "tutorial"

```
<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android'">
    <GoogleServicesJson Include="google-services.json" />
</ItemGroup>

<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-ios'">
    <BundleResource Include="GoogleService-Info.plist" />
</ItemGroup>
```

https://github.com/TobiasBuchholz/Plugin.Firebase#net-maui-support

**Comment by AdamEssenmacher** [comment]
OK yes, you'd want to change those.

**Comment by philm001** [comment]
Maybe this might be able to help. I am double checking my code but when I try to run it on android, this is the error that I am getting
![Capture](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/13646291/d2551e49-1d1e-498a-b51a-07d55b31890c)

**Comment by philm001** [comment]
Do I really need a Crashlytics ID for it to be functioning?

**Comment by AdamEssenmacher** [comment]
Is this something that was previously working on net6/7, or are you trying to add this to a new project for using 8?

**Comment by philm001** [comment]
This is a new project in .NET 8

**Comment by andyzukunft** [comment]
If crashlytics is configured you do need to provide a Crashlytics ID. Either remove this or use a more specified package (e.g. Plugin.Firebase.CloudMessaging). You haven't specified what you are trying to do.

**Comment by philm001** [comment]
Hey guys, sorry, I was able to figure things out and was able to get it working. If I have more issues, I will post a better follow up
