### ISSUE TITLE
xamarin_find_protocol_wrapper_type crash on Crashlytics dashboard.

### ISSUE THREAD

**Issue by mahebisht** [TobiasBuchholz/Plugin.Firebase#291]
There is only xamarin_find_protocol_wrapper_type crash is visible on Crashlytics dashboard using .NET MAUI8 for IOS.
All the crashes and non fatals coming inside xamarin_find_protocol_wrapper_type with no stack trace.

![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/80498223/4b8e6283-91e3-481b-9de1-068a9c1289dc)

This is the stack trace for divide by zero error.

![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/80498223/fda407ec-ea83-4538-899b-ac89466c6a0c)

I am using Plugin.Firebase for Firebase Crashlytics in IOS for .NET MAUI project.
Does .NET MAUI8 support Firebase Crashlytics in IOS?

**Comment by AdamEssenmacher** [comment]
Plugin.Firebase doesn't use these bindings yet, and would be incompatible with these bindings unless you created a fork of Plugin.Firebase and swapped out the Xamarin.iOS.Firebase.* dependencies.

It's my intent to publish a new major version of Plugin.Firebase using these bindings eventually.

**Comment by AdamEssenmacher** [comment]
@mahebisht version 3.0.0 has been published

**Comment by mahebisht** [comment]
Thanks for the update. I am updating the latest version and checking on macbook for IOS.

**Comment by mahebisht** [comment]
After update to latest version 3.0. I am able to build the solution in Windows. 
But unable to build the solution in MacBook. I received following error

Xamarin.Shared.Sdk.targets(3,3): Error: clang++ exited with code 1:
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility50'
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
ld: warning: Could not find or use auto-linked library 'swiftOSLog'
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility51'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
ld: warning: Could not find or use auto-linked library 'swiftUIKit'

**Comment by AdamEssenmacher** [comment]
https://github.com/TobiasBuchholz/Plugin.Firebase/issues/303#issue-2324663841

**Comment by mahebisht** [comment]
Hi Adam,

I added following code. I am able to build the solution in MacBook.

<Target Name="LinkWithSwift" DependsOnTargets="_ParseBundlerArguments;_DetectSdkLocations" BeforeTargets="_LinkNativeExecutable">
    <PropertyGroup>
        <_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('iossimulator-'))">iphonesimulator</_SwiftPlatform>
        <_SwiftPlatform Condition="$(RuntimeIdentifier.StartsWith('ios-'))">iphoneos</_SwiftPlatform>
    </PropertyGroup>
    <ItemGroup>
        <_CustomLinkFlags Include="-L" />
        <_CustomLinkFlags Include="/usr/lib/swift" />
        <_CustomLinkFlags Include="-L" />
        <_CustomLinkFlags Include="$(_SdkDevPath)/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/$(_SwiftPlatform)" />
        <_CustomLinkFlags Include="-Wl,-rpath" />
        <_CustomLinkFlags Include="-Wl,/usr/lib/swift" />
    </ItemGroup>
</Target>

Thanks,
Mahendra

**Comment by AdamEssenmacher** [comment]
@iida-i3 @mahebisht what you're reporting is expected behavior as far as this plugin is concerned. Pugin.Firebase is a thin wrapper around the native client SDKS, which report _native_ crashes. There's no way for these native SDKs to understand managed .NET stack traces or objects (including exceptions). Those are details internal to Mono.

The native SDKs provide an API to report non-fatal errors manually. This plugin exposes those APIs, and even includes some lightweight stack parsing to help make exceptions reported manually to be readable in the Crashlytics dashboard. So, if you want to be reporting details from managed code in the Crashlytics dashboard, that's your option.

**Comment by iida-i3** [comment]
@AdamEssenmacher 

Accodring to your information, I could send readable logs in the Crashlytics dashboard.
I updated [sample project](https://github.com/iida-i3/FirebaseExperiment).

It was a little difficult but good experience for me.
Thank you so much!

**Comment by codychaplin** [comment]
@AdamEssenmacher Just to clarify, does either AdamE.Firebase.iOS.Crashlytics or Plugin.Firebase.Crashlytics 3.0.0 provide readable fatal error stack traces?

**Comment by AdamEssenmacher** [comment]
> @AdamEssenmacher Just to clarify, does either AdamE.Firebase.iOS.Crashlytics or Plugin.Firebase.Crashlytics 3.0.0 provide readable fatal error stack traces?

Depends on what you mean by "readable".  `mono_invoke_unhandled_exception_hook` is readable and explains very well what's happening. That's what the native crash looks like, and it's being reported accurately.

If you want readable managed stack traces, perhaps you could try combining manual reporting with something from https://github.com/dotnet/maui/discussions/653?sort=top#discussioncomment-3434251

**Comment by codychaplin** [comment]
Yes I'm talking about logs with specific function names and line numbers like so:
![Screenshot 2024-07-23 221156](https://github.com/user-attachments/assets/400b0623-07bd-49a1-baf2-77f3d2ea066f)
The above is the type of stack traces I get with the Xamarin.Firebase.iOS.Crashlytics package, and below is what I get with .NET 8 MAUI (same as the original topic of this issue):
![Screenshot 2024-07-23 221447](https://github.com/user-attachments/assets/27f0ee42-9f43-4a31-91ba-416c50b3181f)
I just wanted to clarify whether v3.0.0 added that ability or if it's even possible? Your first comment on this issue suggested that, unless I misinterpreted it. Forgive my ignorance, I'm new to this kind of stuff.

Thank you for the link, I'll most likely utilize `AppDomain.CurrentDomain.UnhandledException`.

**Comment by AdamEssenmacher** [comment]
I don't think what you're observing has anything to do with Xamarin.Firebase.iOS.Crashlytics or AdamE.Firebase.iOS.Crashlytics. The AdamE version is functionally identical--it just ships with current native SDKs.

If you were to install the AdamE.Firebase.iOS.Crashlytics package into a Xamarin app (yes, it's compatible!), you could expect to get crash reports just like the ones you see in your first screenshot. Likewise, if you were to install Xamarin.Firebase.iOS.Crashlytics into an iOS.NET 8.0+ app, you could expect to get crash reports like the ones in your second screenshot.

So what happened to the more useful, .NET-friendly native stack traces? My guess is that iOS.NET introduced some changes around AOT and/or the Mono interpreter (MTouch).

See https://learn.microsoft.com/en-us/dotnet/maui/macios/interpreter?view=net-maui-8.0

> The Mono interpreter overcomes these restrictions while abiding by platform restrictions. It enables you to interpret some parts of your app at runtime, while AOT compiling the rest. However, there are some potential drawbacks to using the interpreter in a production app:
...
> **Native stack traces in crash reports become less useful, because they'll contain generic frames from the interpreter that don't mention the code that's executing. However, managed stack traces won't change.**

In any case, neither `AdamE.Firebase.iOS.Crashlytics` or `Plugin.Firebase` have anything to do with any of it.

**Comment by codychaplin** [comment]
Interesting, so it's more of a .NET problem rather than Firebase. Thanks again for info!

**Comment by Lapinou42** [comment]
Hello everyone, 

I encountered exactly the same issue since long time ago.
Is that fixed ? Do you have more info about that issue ? I searched on Mono / Microsoft Github but found nothing about that.

Thank you guys.

**Comment by codercampos** [comment]
I see that some of you can see some kind of stacktrace. The only thing I can see is this:

![Image](https://github.com/user-attachments/assets/e3d43ee5-2a9c-4b09-a9a4-f1e6b2898295)

I've created a blank project just to not have some kind of conflict between libraries, but at least for unhandled exceptions (or native crashes) is asking you about the dSYM to be submitted manually.

I guess this is not a issue from the library itself but must likely a google stuff and it handles the native reporting.

**Comment by solitajei** [comment]
@codercampos use https://www.nuget.org/packages/AdamE.Firebase.iOS.Crashlytics/ instead - there the dSYM gets uploaded automatically when building IPA etc., as long as the GoogleService-Info.plist has been provided accordingly.
