### ISSUE TITLE
Firestore DateTime retrieval

### ISSUE THREAD

**Issue by rezamohamed** [TobiasBuchholz/Plugin.Firebase#294]
I can save dates into a Firestore doc just fine

![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/18199852/f90a620e-604a-4d42-9834-e62e107b5a92)

however, when I retrieve the date, it doesn't convert correctly:

![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/18199852/e292770e-214d-4a8f-a37a-0d2c89ac1624)

I have the data defined in the model as so currently
        [FirestoreProperty("CreatedDate")]
        public DateTime CreatedDate { get; set; }

If I were to change the type to DateTimeOffset then it would retrieve the date, but it's not the local time that I saved (it's about 5 hours ahead).
        [FirestoreProperty("CreatedDate")]
        public DateTimeOffset CreatedDate { get; set; }

![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/18199852/e5c28dd0-8c10-4aae-a6d8-0009a3e3b71e)

Is this a bug that the **DateTime** type doesn't work properly?

**Comment by AdamEssenmacher** [comment]
Reading a server timestamp into a model property with the DateTime type just isn't currently supported. Not that it couldn't be--the code just hasn't been written for it.
