### ISSUE TITLE
"java" exited with code 1. (MSB6006)

### ISSUE THREAD

**Issue by sattasundar** [TobiasBuchholz/Plugin.Firebase#3]
Have latest Xamarin.Forms 5

After installing package successfully, I tried to build solution but I am getting this error.

"java" exited with code 1. (MSB6006)

**Build Output
----------------
Target _CreateBaseApk:
    Touching "obj/Release/android/bin/packaged_resources".
Target _CompileJava:
    /Users/hiteshmalhotra/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25/bin/javac -J-Dfile.encoding=UTF8 "@/var/folders/wr/6wc59d8900l4cgq4tb300hpc0000gq/T/tmp243da4f6.tmp" -target 1.8 -source 1.8 
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    Creating "obj/Release/_javac.stamp" because "AlwaysCreate" was specified.
Target _CompileToDalvik:
    /Users/hiteshmalhotra/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25/bin/java -Xmx1G -classpath /Library/Frameworks/Xamarin.Android.framework/Libraries/xbuild/Xamarin/Android/r8.jar com.android.tools.r8.R8 --release --min-api 23 --output obj/Release/android/bin/ --lib /Users/hiteshmalhotra/Library/Android/sdk/platforms/android-30/android.jar --lib /Users/hiteshmalhotra/Library/Android/sdk/platforms/android-30/optional/org.apache.http.legacy.jar obj/Release/android/bin/classes.zip /Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v11.0/mono.android.jar /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/java_runtime.jar /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.annotation/1.1.0.8/buildTransitive/monoandroid90/../../jar/androidx.annotation.annotation.jar /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.collection/1.1.0.6/buildTransitive/monoandroid90/../../jar/androidx.collection.collection.jar /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.lifecycle.common/2.2.0.4/buildTransitive/monoandroid90/../../jar/androidx.lifecycle.lifecycle-common.jar /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.arch.core.common/2.1.0.7/buildTransitive/monoandroid90/../../jar/androidx.arch.core.core-common.jar /Users/hiteshmalhotra/.nuget/packages/xamarin.google.guava.listenablefuture/1.0.0.2/buildTransitive/monoandroid50/guava-listenablefuture.jar obj/Release/lp/135/jl/classes.jar obj/Release/lp/132/jl/classes.jar obj/Release/lp/92/jl/__reference__guava.jar obj/Release/lp/157/jl/classes.jar obj/Release/lp/150/jl/classes.jar obj/Release/lp/159/jl/classes.jar obj/Release/lp/161/jl/classes.jar obj/Release/lp/133/jl/classes.jar obj/Release/lp/93/jl/guava-failureaccess.jar obj/Release/lp/134/jl/classes.jar obj/Release/lp/158/jl/classes.jar obj/Release/lp/151/jl/classes.jar obj/Release/lp/156/jl/classes.jar obj/Release/lp/9/jl/okio.jar obj/Release/lp/145/jl/classes.jar obj/Release/lp/142/jl/classes.jar obj/Release/lp/7/jl/okhttp.jar obj/Release/lp/129/jl/classes.jar obj/Release/lp/116/jl/grpc-protobuf-lite-1.28.0.jar obj/Release/lp/118/jl/opencensus-api-0.21.0.jar obj/Release/lp/127/jl/classes.jar obj/Release/lp/120/jl/opencensus-api-0.19.0.jar obj/Release/lp/143/jl/classes.jar obj/Release/lp/144/jl/classes.jar obj/Release/lp/1/jl/bolts-tasks.jar obj/Release/lp/8/jl/okhttp3.jar obj/Release/lp/121/jl/javax-inject.jar obj/Release/lp/119/jl/opencensus-contrib-grpc-metrics-0.21.0.jar obj/Release/lp/72/jl/firebase-encoders.jar obj/Release/lp/126/jl/classes.jar obj/Release/lp/128/jl/classes.jar obj/Release/lp/117/jl/grpc-stub-1.28.0.jar obj/Release/lp/153/jl/classes.jar obj/Release/lp/154/jl/classes.jar obj/Release/lp/131/jl/classes.jar obj/Release/lp/91/jl/dagger.jar obj/Release/lp/136/jl/classes.jar obj/Release/lp/138/jl/classes.jar obj/Release/lp/155/jl/classes.jar obj/Release/lp/152/jl/classes.jar obj/Release/lp/139/jl/classes.jar obj/Release/lp/137/jl/classes.jar obj/Release/lp/63/jl/firebase-annotations.jar obj/Release/lp/130/jl/classes.jar obj/Release/lp/112/jl/grpc-api-1.28.0.jar obj/Release/lp/115/jl/grpc-okhttp-1.28.0.jar obj/Release/lp/123/jl/classes.jar obj/Release/lp/124/jl/classes.jar obj/Release/lp/148/jl/classes.jar obj/Release/lp/141/jl/classes.jar obj/Release/lp/4/jl/gson.jar obj/Release/lp/3/jl/zxing.core.jar obj/Release/lp/146/jl/classes.jar obj/Release/lp/125/jl/classes.jar obj/Release/lp/122/jl/protobuf-javalite.jar obj/Release/lp/114/jl/grpc-core-1.28.0.jar obj/Release/lp/113/jl/grpc-context-1.28.0.jar obj/Release/lp/147/jl/classes.jar obj/Release/lp/2/jl/formsviewgroup.jar obj/Release/lp/140/jl/classes.jar obj/Release/lp/149/jl/classes.jar obj/Release/lp/61/jl/bin/classes.jar obj/Release/lp/95/jl/bin/classes.jar obj/Release/lp/59/jl/bin/classes.jar obj/Release/lp/66/jl/bin/classes.jar obj/Release/lp/104/jl/bin/classes.jar obj/Release/lp/68/jl/bin/classes.jar obj/Release/lp/103/jl/bin/classes.jar obj/Release/lp/57/jl/bin/classes.jar obj/Release/lp/102/jl/bin/classes.jar obj/Release/lp/69/jl/bin/classes.jar obj/Release/lp/56/jl/bin/classes.jar obj/Release/lp/105/jl/bin/classes.jar obj/Release/lp/58/jl/bin/classes.jar obj/Release/lp/67/jl/bin/classes.jar obj/Release/lp/60/jl/bin/classes.jar obj/Release/lp/0/jl/bin/classes.jar obj/Release/lp/89/jl/bin/classes.jar obj/Release/lp/111/jl/bin/classes.jar obj/Release/lp/73/jl/bin/classes.jar obj/Release/lp/87/jl/bin/classes.jar obj/Release/lp/80/jl/bin/classes.jar obj/Release/lp/74/jl/bin/classes.jar obj/Release/lp/75/jl/bin/classes.jar obj/Release/lp/81/jl/bin/classes.jar obj/Release/lp/110/jl/bin/classes.jar obj/Release/lp/88/jl/bin/classes.jar obj/Release/lp/65/jl/bin/classes.jar obj/Release/lp/96/jl/bin/classes.jar obj/Release/lp/109/jl/bin/classes.jar obj/Release/lp/100/jl/bin/classes.jar obj/Release/lp/54/jl/bin/classes.jar obj/Release/lp/107/jl/bin/classes.jar obj/Release/lp/98/jl/bin/classes.jar obj/Release/lp/53/jl/bin/classes.jar obj/Release/lp/106/jl/bin/classes.jar obj/Release/lp/99/jl/bin/classes.jar obj/Release/lp/101/jl/bin/classes.jar obj/Release/lp/55/jl/bin/classes.jar obj/Release/lp/97/jl/bin/classes.jar obj/Release/lp/108/jl/bin/classes.jar obj/Release/lp/64/jl/bin/classes.jar obj/Release/lp/79/jl/bin/classes.jar obj/Release/lp/83/jl/bin/classes.jar obj/Release/lp/77/jl/bin/classes.jar obj/Release/lp/70/jl/bin/classes.jar obj/Release/lp/84/jl/bin/classes.jar obj/Release/lp/71/jl/bin/classes.jar obj/Release/lp/76/jl/bin/classes.jar obj/Release/lp/82/jl/bin/classes.jar obj/Release/lp/78/jl/bin/classes.jar --no-tree-shaking --no-minification --pg-conf /var/folders/wr/6wc59d8900l4cgq4tb300hpc0000gq/T/tmp4dfeda8c.tmp --pg-conf /Users/hiteshmalhotra/Library/Android/sdk/tools/proguard/proguard-android.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.versionedparcelable/1.1.1.6/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.lifecycle.runtime/2.2.0.4/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.core/1.3.2.1/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.savedstate/1.1.0.4-alpha01/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.lifecycle.viewmodel/2.2.0.4/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.lifecycle.viewmodelsavedstate/2.2.0.4/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.fragment/1.2.5.4/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.recyclerview/1.1.0.5/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.vectordrawable.animated/1.1.0.5/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.transition/1.3.1.5/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.coordinatorlayout/1.1.0.6/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.appcompat/1.2.0.5/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.google.android.material/1.1.0.5/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.androidx.media/1.2.1.1/buildTransitive/monoandroid90/../../proguard/proguard.txt --pg-conf /Users/hiteshmalhotra/.nuget/packages/xamarin.forms/5.0.0.1874/buildTransitive/MonoAndroid10/proguard.cfg 
    Error in /Users/hiteshmalhotra/.nuget/packages/xamarin.google.guava.listenablefuture/1.0.0.2/buildTransitive/monoandroid50/guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class:
    Type com.google.common.util.concurrent.ListenableFuture is defined multiple times: /Users/hiteshmalhotra/.nuget/packages/xamarin.google.guava.listenablefuture/1.0.0.2/buildTransitive/monoandroid50/guava-listenablefuture.jar:com/google/common/util/concurrent/ListenableFuture.class, obj/Release/lp/92/jl/__reference__guava.jar:com/google/common/util/concurrent/ListenableFuture.class
    Compilation failed
    /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.D8.targets(51,5): error MSB6006: "java" exited with code 1.
Done building target "_CompileToDalvik" in project "XamDemo.Android.csproj" -- FAILED.

Done building project "XamDemo.Android.csproj" -- FAILED.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:43.10

Build FAILED.

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.D8.targets(51,5): error MSB6006: "java" exited with code 1.
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:39.68

========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Build: 1 error, 0 warnings

**Comment by TobiasBuchholz** [comment]
Try to add the following `PackageReference` to the .csproj file of your android project:

```xml
<PackageReference Include="Xamarin.Google.Guava.ListenableFuture" Version="1.0.0.2" ExcludeAssets="build;buildTransitive" />
```

I've added this specific step to the [README](https://github.com/TobiasBuchholz/Plugin.Firebase#android-specifics) file.

**Comment by sattasundar** [comment]
Thanks Budyy that build error is resolved.

Now I got a Challenge; 

**MainActivity
----------------
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
    {
        protected override void OnCreate(Bundle savedInstanceState)
        {
            TabLayoutResource = Resource.Layout.Tabbar;
            ToolbarResource = Resource.Layout.Toolbar;

            base.OnCreate(savedInstanceState);

            Xamarin.Essentials.Platform.Init(this, savedInstanceState);
            global::Xamarin.Forms.Forms.Init(this, savedInstanceState);
            FirebaseApp.InitializeApp(this);
            CrossFirebase.Initialize(this, savedInstanceState, CreateCrossFirebaseSettings());
            HandleIntent(Intent);
            LoadApplication(new App());
        }

        private static CrossFirebaseSettings CreateCrossFirebaseSettings()
        {
            return new CrossFirebaseSettings(
                isAnalyticsEnabled:true,
                isAuthEnabled:true,
                isCloudMessagingEnabled:true,
                isDynamicLinksEnabled: true,
                isFirestoreEnabled: true,
                isFunctionsEnabled: true,
                isRemoteConfigEnabled: true,
                isStorageEnabled: true
                //facebookId: "", //Facebook client id
                //facebookAppName: "", // App Name over facebook
                //googleRequestIdToken: ""
                );
        }

        private static void HandleIntent(Intent intent)
        {
            FirebaseCloudMessagingImplementation.OnNewIntent(intent);
            FirebaseDynamicLinksImplementation.HandleDynamicLinkAsync(intent);
        }

        public override void OnRequestPermissionsResult(int requestCode, string[] permissions, [GeneratedEnum] Android.Content.PM.Permission[] grantResults)
        {
            Xamarin.Essentials.Platform.OnRequestPermissionsResult(requestCode, permissions, grantResults);

            base.OnRequestPermissionsResult(requestCode, permissions, grantResults);
        }

        protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            FirebaseAuthImplementation.HandleActivityResultAsync(requestCode, resultCode, data);
        }
        
        protected override void OnNewIntent(Intent intent)
        {
            base.OnNewIntent(intent);
            HandleIntent(intent);
        }
    }

**MainPage.xaml.cs
    ---------------------
     public partial class MainPage : ContentPage
    {
        private readonly Lazy<IFirebaseAuth> _firebaseAuth;
        private IFirebaseAuth _fireAuth;
        public MainPage()
        {
            InitializeComponent();
            _firebaseAuth = new Lazy<IFirebaseAuth>(CreateFirebaseAuth);
        }
        private static IFirebaseAuth CreateFirebaseAuth() =>
            CrossFirebaseAuth.Current;
        async void ClickMe(System.Object sender, System.EventArgs e)
        {
            try
            {
                _fireAuth = _firebaseAuth.Value;
                await _fireAuth.VerifyPhoneNumberAsync(phoneEntry.Text);
            }
            catch(Exception ex)
            {
                await DisplayAlert("Error", ex.Message, "Okay");
            }
        }
    }

    Is anything I am missing? Because I getting the exception alert which is in screenshot;
<img width="1680" alt="Screenshot 2021-01-19 at 5 48 53 PM" src="https://user-images.githubusercontent.com/62828724/105033817-9f4dfe80-5a7e-11eb-8f37-6f21358af707.png">
