### ISSUE TITLE
Unable to update from 2.0.4 to 3.0.0

### ISSUE THREAD

**Issue by RsZoli** [TobiasBuchholz/Plugin.Firebase#305]
When i'm trying to update the NuGet from 2.0.4 to 3.0.0 i got the following error:

`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\.nuget\adame.firebase.ios.core\10.24.0\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.`

There is only one file at that path:

![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/28480037/eef0afb9-a3f2-4741-8d5f-02fab34135ba)

The downloads are finishing okay as far as i can tell:

GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/index.json
OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/index.json 296ms
CACHE https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/index.json
GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0.1/adame.firebase.ios.core.10.24.0.1.nupkg
OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0.1/adame.firebase.ios.core.10.24.0.1.nupkg 99ms
CACHE https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0.1/adame.firebase.ios.core.10.24.0.1.nupkg
GET https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0/adame.firebase.ios.core.10.24.0.nupkg
OK https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0/adame.firebase.ios.core.10.24.0.nupkg 59ms
CACHE https://api.nuget.org/v3-flatcontainer/adame.firebase.ios.core/10.24.0/adame.firebase.ios.core.10.24.0.nupkg

**Comment by AdamEssenmacher** [comment]
Probably this: https://github.com/TobiasBuchholz/Plugin.Firebase?tab=readme-ov-file#troubleshooting

**Comment by RsZoli** [comment]
@AdamEssenmacher sadly, no! this is my full path: "c:\.nuget\adame.firebase.ios.core\10.24.0\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\"

It is only 216 characters!

**Comment by AdamEssenmacher** [comment]
Is the file actually there?

**Comment by RsZoli** [comment]
@AdamEssenmacher No, its not! Thats why i included a screenshot of the folder!

**Comment by AdamEssenmacher** [comment]
OK.

`C:\.nuget\adame.firebase.ios.core\10.24.0\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface`

is 265 characters. This is almost definitely the long file path issue I liked above.

https://github.com/TobiasBuchholz/Plugin.Firebase?tab=readme-ov-file#troubleshooting
https://github.com/dotnet/maui/issues/17828
https://developercommunity.visualstudio.com/t/Allow-building-running-and-debugging-a/351628

**Comment by RsZoli** [comment]
@AdamEssenmacher You are right, i'm sorry! I was lazy and asked the ChatGPT regarding how many characters it has!

However i have long path enabled, i encountered this anomlaly before! So if you can tell me how i can i download the files needed manually, i'll just do that!

Thank you!

**Comment by AdamEssenmacher** [comment]
Getting past the long path issue involves several steps, including clearing your local nuget caches and ensuring that your initial package restores are done via command line. These are well documented in the MAUI issue linked above.

**Comment by AdamEssenmacher** [comment]
The file didn't get extracted because of the long file path issue.

**Comment by RsZoli** [comment]
Well i managed to update the NuGet, shortened the path even more, now the missing file is indeed there, however the project won't build:

`C:\.n\xamarin.build.download\0.11.4\buildTransitive\Xamarin.Build.Download.targets(52,3): error : Could not find 7zip.exe in Xamarin installation`

**Comment by Skarzag** [comment]
We have the same problem on our project, It work with Android but not with iOS.
I tried a lot of workaround suggested here and there.

- With dotnet restore command in command terminal i got the same message as @RsZoli
- With Visual Studio debug, 
![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/76732935/cac41136-4996-4082-abb9-15435be79919)
