### ISSUE TITLE
clang++ exited with code 1 after upgrade to 3.0.0

### ISSUE THREAD

**Issue by zwikk** [TobiasBuchholz/Plugin.Firebase#309]
After upgrading from 2.0.14 to 3.0.0 my MAUI iOS app build fails with the following. Failure occurs in devops pipeline only, local build works fine

```
error : clang++ exited with code 1: 
error : ld: warning: Could not find or use auto-linked library 'swiftCore' 
error : ld: warning: Could not find or use auto-linked library 'swiftCompatibility50' 
error : ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics' 
error : ld: warning: Could not find or use auto-linked library 'swiftCoreImage' 
error : ld: warning: Could not find or use auto-linked library 'swiftFileProvider' 
error : ld: warning: Could not find or use auto-linked library 'swiftOSLog' 
error : ld: warning: Could not find or use auto-linked library 'swiftObjectiveC' 
error : ld: warning: Could not find or use auto-linked library 'swiftFoundation' 
error : ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements' 
error : ld: warning: Could not find or use auto-linked library 'swiftDarwin' 
error : ld: warning: Could not find or use auto-linked library 'swiftCompatibility51' 
error : ld: warning: Could not find or use auto-linked library 'swiftQuartzCore' 
error : ld: warning: Could not find or use auto-linked library 'swiftUIKit' 
error : ld: warning: Could not find or use auto-linked library 'swif 
```

Error looks exactly like this [report on stackoverflow](https://stackoverflow.com/questions/78605885/how-to-resolve-clang-error-missing-auto-linked-swift-libraries?noredirect=1#comment138590797_78605885)

Question is why is there a swift dependency, while version 2.* worked fine without it?

**Comment by AdamEssenmacher** [comment]
> Question is why is there a swift dependency, while version 2.* worked fine without it?

2.* was built on native SDK versions 8.10. 3.* is built on 10.24.

https://github.com/TobiasBuchholz/Plugin.Firebase?tab=readme-ov-file#version-300-notes

https://github.com/TobiasBuchholz/Plugin.Firebase?tab=readme-ov-file#basic-setup

https://github.com/TobiasBuchholz/Plugin.Firebase/issues/303

**Comment by zwikk** [comment]
Ah, thanks, that makes sense.
