### ISSUE TITLE
The utter annoying path-length problematic: Can't build .ipa file on remote Mac device

### ISSUE THREAD

**Issue by baconsplit** [TobiasBuchholz/Plugin.Firebase#314]
Hello,
I know this issue is often discussed already and I applied every workaround mentioned on here, with limited success.
I am talking about the path-length problem on Windows builds and especially Visual Studio and Visual Studio using a 32-bit version of MSBuild (or whatever).

Now, if we nuget restore, dotnet restore and dotnet publish all via Command Line, we can build our .NET MAUI Project for iOS with "no problem".

But we are having problems connecting it to our Apple development system which is needed to finally build the .ipa file for the App Store.
We can only connect our Visual Studio to the Apple deployment system and start the build there, and to no surprise, Visual Studio fails to move some files generated deep in some %APPDATA% path because is simply hosts too long path-names.

Are we missing something here, how could we mitigate even this last step and successfully build our .ipa file?

The NuGet packages are up-to-date and already use the AdamE iOS.* dependencies.

I kindly ask for any help and can provide more information if needed, this is the comical worst problem any developer can face in 2024. Path-length, really Microsoft? .. (referring to this ticket, which opened in 2018 https://developercommunity.visualstudio.com/t/allow-building-running-and-debugging-a-net-applica/351628)

**Comment by AdamEssenmacher** [comment]
https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/blob/main/Readme.md#windows--visual-studio-long-path-issue

**Comment by trsted** [comment]
Hey sorry, I forgot to respond! Thanks for the quick answer and trying to help out with the problem.
We settled on utilizing our Mac more now and try to build the .ipa directly on it. Today's test worked okay with the dotnet CLI. So yeah, this issue can be closed!

Also thanks for updating the Readme on a possible solution on the XCFrameworks, unfortunately this isn't anything near my development experience I've done so far and we rather need a quick solution for Push Notifications on our .NET MAUI App.

**Comment by baconsplit** [comment]
Hey sorry, I forgot to respond! Thanks for the quick answer and trying to help out with the problem.
We settled on utilizing our Mac more now and try to build the .ipa directly on it. Today's test worked okay with the dotnet CLI. So yeah, this issue can be closed!

Also thanks for updating the Readme on a possible solution on the XCFrameworks, unfortunately this isn't anything near my development experience I've done so far and we rather need a quick solution for Push Notifications on our .NET MAUI App.
