### ISSUE TITLE
Cannot install the nuget package

### ISSUE THREAD

**Issue by fbua** [TobiasBuchholz/Plugin.Firebase#315]
I was trying to install the CloudMessaging plugin but I got this error from nuget

Could not find a part of the path 'E:\n\adame.firebase.ios.core\10.24.0\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'

I also tried to add the LongPathSupport on Win11 and changed the nuget location.

**Comment by AdamEssenmacher** [comment]
It's the long-path issue.

https://github.com/AdamEssenmacher/GoogleApisForiOSComponents/blob/main/Readme.md#windows--visual-studio-long-path-issue
