### ISSUE TITLE
Unable to update from 2.0.3  to 3.0.0 when the project has referens to CommunityToolkit.Maui.MediaElement

### ISSUE THREAD

**Issue by JoacimWall** [TobiasBuchholz/Plugin.Firebase#317]
Hi try to update to 3.0.0 result in error and unable build. I am on a Mac 

The app has this packagereferences.
  before 
Plugin.Firebase.CloudMessaging" Version="2.0.3" 
Plugin.Firebase.Analytics" Version="2.0.1" 
CommunityToolkit.Maui.MediaElement" Version="4.0.0"
Now
Plugin.Firebase.CloudMessaging" Version="3.0.0" 
Plugin.Firebase.Analytics" Version="3.0.0"
CommunityToolkit.Maui.MediaElement" Version="4.0.0"

Error:
dotnet build /Users/joacimwall/Projects/MediaPlayer/MediaPlayer.sln /target:MediaPlayer /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="Any CPU" 
  Determining projects to restore...
  All projects are up-to-date for restore.
  Detected signing identity:
          
    Bundle Id: com.companyname.mediaplayer
    App Id: com.companyname.mediaplayer
  Detected signing identity:
          
    Bundle Id: com.companyname.mediaplayer
    App Id: com.companyname.mediaplayer
  MediaPlayer -> /Users/joacimwall/Projects/MediaPlayer/bin/Debug/net8.0-maccatalyst/maccatalyst-arm64/MediaPlayer.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Optimizing assemblies for size. This process might take a while.
  MediaPlayer -> /Users/joacimwall/Projects/MediaPlayer/bin/Debug/net8.0-android/MediaPlayer.dll
  MediaPlayer -> /Users/joacimwall/Projects/MediaPlayer/bin/Debug/net8.0-ios/iossimulator-arm64/MediaPlayer.dll
  Optimizing assemblies for size may change the behavior of the app. Be sure to test after publishing. See: https://aka.ms/dotnet-illink
  Optimizing assemblies for size. This process might take a while.
/Users/joacimwall/Library/Caches/XamarinBuildDownload/FAnlytcs-10.24.0/FirebaseAnalytics-10.24.0/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-simulator/FirebaseAnalytics.framework/FirebaseAnalytics : warning MT7091: The framework /Users/joacimwall/Library/Caches/XamarinBuildDownload/FAnlytcs-10.24.0/FirebaseAnalytics-10.24.0/Frameworks/FirebaseAnalytics.xcframework/ios-arm64_x86_64-simulator/FirebaseAnalytics.framework is a framework of static libraries, and will not be copied to the app. [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/Users/joacimwall/Library/Caches/XamarinBuildDownload/GAppM-10.24.0/GoogleAppMeasurement-10.24.0/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_x86_64-simulator/GoogleAppMeasurement.framework/GoogleAppMeasurement : warning MT7091: The framework /Users/joacimwall/Library/Caches/XamarinBuildDownload/GAppM-10.24.0/GoogleAppMeasurement-10.24.0/Frameworks/GoogleAppMeasurement.xcframework/ios-arm64_x86_64-simulator/GoogleAppMeasurement.framework is a framework of static libraries, and will not be copied to the app. [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
  Tool xcrun execution finished (exit code = 1).
          
  ld: warning: Could not find or use auto-linked library 'swiftCore'
  ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
  ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
  ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
  ld: warning: Could not find or use auto-linked library 'swiftOSLog'
  ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
  ld: warning: Could not find or use auto-linked library 'swiftFoundation'
  ld: warning: Could not find or use auto-linked library 'swiftUIKit'
  ld: warning: Could not find or use auto-linked library 'swiftDarwin'
  ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
  ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
  ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency'
  ld: warning: Could not find or use auto-linked library 'swiftMetal'
  ld: warning: Could not find or use auto-linked library 'swiftDispatch'
  ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
  ld: warning: Could not find or use auto-linked library 'swiftDataDetection'
  ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
  ld: warning: Could not find or use auto-linked library 'swift_StringProcessing'
  ld: warning: Could not find or use auto-linked library 'swiftos'
  Undefined symbols for architecture arm64:
    "_$sSS4hash4intoys6HasherVz_tF", referenced from:
        _$ss22__RawDictionaryStorageC4findys10_HashTableV6BucketV6bucket_Sb5foundtxSHRzlFSS_Tg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_$sSSN", referenced from:
        _$s17FirebaseAnalytics06LoggedB8ModifierV4body7contentQr7SwiftUI05_ViewD8_ContentVyACG_tFyycfU_ in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$ss17_NativeDictionaryV12mutatingFind_8isUniques10_HashTableV6BucketV6bucket_Sb5foundtx_SbtFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_$sSSSHsWP", referenced from:
        _$s17FirebaseAnalytics06LoggedB8ModifierV4body7contentQr7SwiftUI05_ViewD8_ContentVyACG_tFyycfU_ in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_$sSzsE11descriptionSSvg", referenced from:
        _$sSo12FIRAnalyticsC17FirebaseAnalyticsE14logTransactionyy8StoreKit0E0VFZ in FirebaseAnalytics(Analytics+StoreKit.o)
    "_$ss18_DictionaryStorageC4copy8originalAByxq_Gs05__RawaB0C_tFZ", referenced from:
        _$ss17_NativeDictionaryV4copyyyFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_$ss18_DictionaryStorageC6resize8original8capacity4moveAByxq_Gs05__RawaB0C_SiSbtFZ", referenced from:
        _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_$ss18_DictionaryStorageCMn", referenced from:
        _symbolic _____ySSypG s18_DictionaryStorageC in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_$ss27_stringCompareWithSmolCheck__9expectingSbs11_StringGutsV_ADs01_G16ComparisonResultOtF", referenced from:
        _$ss22__RawDictionaryStorageC4find_9hashValues10_HashTableV6BucketV6bucket_Sb5foundtx_SitSHRzlFSS_Tg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_$ss53KEY_TYPE_OF_DICTIONARY_VIOLATES_HASHABLE_REQUIREMENTSys5NeverOypXpF", referenced from:
        _$ss17_NativeDictionaryV12mutatingFind_8isUniques10_HashTableV6BucketV6bucket_Sb5foundtx_SbtFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_$ss6HasherV5_seedABSi_tcfC", referenced from:
        _$ss22__RawDictionaryStorageC4findys10_HashTableV6BucketV6bucket_Sb5foundtxSHRzlFSS_Tg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_$ss6HasherV9_finalizeSiyF", referenced from:
        _$ss22__RawDictionaryStorageC4findys10_HashTableV6BucketV6bucket_Sb5foundtxSHRzlFSS_Tg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_$ss6UInt64VN", referenced from:
        _$sSo12FIRAnalyticsC17FirebaseAnalyticsE14logTransactionyy8StoreKit0E0VFZ in FirebaseAnalytics(Analytics+StoreKit.o)
        _$ss6UInt64VABSzsWl in FirebaseAnalytics(Analytics+StoreKit.o)
    "_$ss6UInt64VSzsMc", referenced from:
        _$ss6UInt64VABSzsWl in FirebaseAnalytics(Analytics+StoreKit.o)
    "_$sypN", referenced from:
        _$s17FirebaseAnalytics06LoggedB8ModifierV4body7contentQr7SwiftUI05_ViewD8_ContentVyACG_tFyycfU_ in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$sypWOb in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$sypWOc in FirebaseAnalytics(Analytics+SwiftUI.o)
    "__swift_FORCE_LOAD_$_swiftCompatibilityConcurrency", referenced from:
        __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftCompatibilityConcurrency_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
        __swift_FORCE_LOAD_$_swiftCoreFoundation_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftCoreFoundation_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftCoreGraphics", referenced from:
        __swift_FORCE_LOAD_$_swiftCoreGraphics_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftCoreGraphics_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreGraphics_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftCoreImage", referenced from:
        __swift_FORCE_LOAD_$_swiftCoreImage_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftCoreImage_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreImage_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
        __swift_FORCE_LOAD_$_swiftDarwin_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftDarwin_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftDataDetection", referenced from:
        __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftDataDetection_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftDispatch", referenced from:
        __swift_FORCE_LOAD_$_swiftDispatch_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftDispatch_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftDispatch_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftFileProvider", referenced from:
        __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftFileProvider_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftMetal", referenced from:
        __swift_FORCE_LOAD_$_swiftMetal_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftMetal_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftMetal_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftOSLog", referenced from:
        __swift_FORCE_LOAD_$_swiftOSLog_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftOSLog_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftOSLog_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftObjectiveC", referenced from:
        __swift_FORCE_LOAD_$_swiftObjectiveC_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftObjectiveC_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftObjectiveC_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftQuartzCore", referenced from:
        __swift_FORCE_LOAD_$_swiftQuartzCore_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftQuartzCore_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftQuartzCore_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers", referenced from:
        __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftUniformTypeIdentifiers_$_FirebaseAnalytics)
    "__swift_FORCE_LOAD_$_swiftos", referenced from:
        __swift_FORCE_LOAD_$_swiftos_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+StoreKit.o)
        __swift_FORCE_LOAD_$_swiftos_$_FirebaseAnalytics in FirebaseAnalytics(Analytics+SwiftUI.o)
       (maybe you meant: __swift_FORCE_LOAD_$_swiftos_$_FirebaseAnalytics)
    "_swift_allocObject", referenced from:
        _$s17FirebaseAnalytics06LoggedB8ModifierV7SwiftUI04ViewD0AadEP4body7content4BodyQzAD01_gD8_ContentVyxG_tFTW in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_swift_bridgeObjectRelease", referenced from:
        _$sSo12FIRAnalyticsC17FirebaseAnalyticsE14logTransactionyy8StoreKit0E0VFZ in FirebaseAnalytics(Analytics+StoreKit.o)
        _$s17FirebaseAnalytics06LoggedB8ModifierV4body7contentQr7SwiftUI05_ViewD8_ContentVyACG_tFyycfU_ in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$s17FirebaseAnalytics06LoggedB8ModifierVwxx in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$s17FirebaseAnalytics06LoggedB8ModifierVwca in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$s17FirebaseAnalytics06LoggedB8ModifierVwta in FirebaseAnalytics(Analytics+SwiftUI.o)
        l_objectdestroy in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_swift_bridgeObjectRetain", referenced from:
        _$s17FirebaseAnalytics06LoggedB8ModifierV4body7contentQr7SwiftUI05_ViewD8_ContentVyACG_tFyycfU_ in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$s17FirebaseAnalytics06LoggedB8ModifierVwcp in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$s17FirebaseAnalytics06LoggedB8ModifierVwca in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$sSSWOr in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$sSDySSypGWOr in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$ss17_NativeDictionaryV4copyyyFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
        ...
    "_swift_deallocObject", referenced from:
        l_objectdestroy in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_swift_getOpaqueTypeConformance", referenced from:
        _$s17FirebaseAnalytics06LoggedB8ModifierV7SwiftUI04ViewD0AA4BodyAdEP_AD0G0PWT in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_swift_getTypeByMangledNameInContext", referenced from:
        ___swift_instantiateConcreteTypeFromMangledName in FirebaseAnalytics(Analytics+StoreKit.o)
    "_swift_getTypeByMangledNameInContextInMetadataState", referenced from:
        ___swift_instantiateConcreteTypeFromMangledNameAbstract in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_swift_getWitnessTable", referenced from:
        _$ss6UInt64VABSzsWl in FirebaseAnalytics(Analytics+StoreKit.o)
        l_get_witness_table 7SwiftUI4ViewRzlAA15ModifiedContentVyx17FirebaseAnalytics06LoggedG8ModifierVGAaBHPxAaBHD1__AgA0cI0HPyHCHC in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$s17FirebaseAnalytics06LoggedB8ModifierVAC7SwiftUI04ViewD0AAWl in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$s7SwiftUI15ModifiedContentVyAA014_ViewModifier_D0Vy17FirebaseAnalytics06LoggedhF0VGAA017_AppearanceActionF0VGACyxq_GAA0E0A2aNRzAA0eF0R_rlWl in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$s7SwiftUI21_ViewModifier_ContentVy17FirebaseAnalytics06LoggedgD0VGACyxGAA0C0AAWl in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_swift_isUniquelyReferenced_nonNull_native", referenced from:
        _$s17FirebaseAnalytics06LoggedB8ModifierV4body7contentQr7SwiftUI05_ViewD8_ContentVyACG_tFyycfU_ in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_swift_release", referenced from:
        _$s10Foundation4DataV15_RepresentationOWOe in FirebaseAnalytics(Analytics+StoreKit.o)
        ___swift_destroy_boxed_opaque_existential_0 in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$ss17_NativeDictionaryV4copyyyFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
    "_swift_retain", referenced from:
        _$s17FirebaseAnalytics06LoggedB8ModifierVwCP in FirebaseAnalytics(Analytics+SwiftUI.o)
        _$ss17_NativeDictionaryV20_copyOrMoveAndResize8capacity12moveElementsySi_SbtFSS_ypTg5 in FirebaseAnalytics(Analytics+SwiftUI.o)
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : clang++ exited with code 1: [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftCore' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftCoreImage' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftFileProvider' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftOSLog' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftObjectiveC' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftFoundation' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftUIKit' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftDarwin' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftQuartzCore' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftCompatibilityConcurrency' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftMetal' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error : ld: warning: Could not find or use auto-linked library 'swiftDispatch' [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]
/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8053/targets/Xamarin.Shared.Sdk.targets(1560,3): error :  [/Users/joacimwall/Projects/MediaPlayer/MediaPlayer.csproj::TargetFramework=net8.0-ios]

**Comment by AdamEssenmacher** [comment]
Please check the basic setup instructions in the project readme.
