### ISSUE TITLE
FirebaseAnalytics null exception on Android .NET8

### ISSUE THREAD

**Issue by lhughey** [TobiasBuchholz/Plugin.Firebase#318]
I'm noticing a NullRef exception when attempting to access the CrossFirebaseAnalytics.Current object on Droid. Analytics work on iOS.

**The error message**
```
android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object.
07-01 12:22:39.547 E/AndroidRuntime(26437):    at Plugin.Firebase.Analytics.FirebaseAnalyticsImplementation.LogEvent(String eventName, IDictionary`2 parameters)
07-01 12:22:39.547 E/AndroidRuntime(26437):    at Plugin.Firebase.Analytics.FirebaseAnalyticsImplementation.LogEvent(String eventName, ValueTuple`2[] parameters)
```

I have stepped through the error to ensure the issue isn't related to the Dictionary object. The error is due to the FirebaseAnalyticsImplementation being null, but it only happening when accessing a method of the object.

**Environment**
.NET 8
Android 33
Plugin.Firebase 3.0
Mac Sonoma 14.5

Here is how I'm calling the object on the onAppearing on the MainPage

```    
var firebaseAnalytics = CrossFirebaseAnalytics.Current;
//calling another object below to ensure the initialization of Firebase singletons are working properly
 var firebaseFirestore = CrossFirebaseFirestore.Current;
```

The details of my android.OnCreate are here:
```
CrossFirebase.Initialize(activity);
CrossFirebaseCrashlytics.Current.SetCrashlyticsCollectionEnabled(true);
```

The MauiBuilder details are as such:
```
builder.Services.AddSingleton(_ => CrossFirebaseAuth.Current);
// builder.Services.AddSingleton(_ => CrossFirebaseAuthFacebook.Current);
// builder.Services.AddSingleton(_ => CrossFirebaseAuthGoogle.Current);
builder.Services.AddSingleton(_ => CrossFirebaseCloudMessaging.Current);
builder.Services.AddSingleton(_ => CrossFirebaseDynamicLinks.Current);
builder.Services.AddSingleton(_ => CrossFirebaseFunctions.Current);
builder.Services.AddSingleton(_ => CrossFirebaseStorage.Current);
builder.Services.AddSingleton(_ => CrossFirebaseRemoteConfig.Current);
builder.Services.AddSingleton(_ => CrossFirebaseAnalytics.Current);

**Comment by AdamEssenmacher** [comment]
https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/docs/analytics.md ?

**Comment by CostasAthan** [comment]
Same issue here. This line of code: `CrossFirebaseAnalytics.Current.IsAnalyticsCollectionEnabled = true;` throws:

> System.NullReferenceException: 'Object reference not set to an instance of an object.'

I'm using .NET 8 and I'm targeting API Level 34,

**Comment by AdamEssenmacher** [comment]
Does the above linked documentation help?

**Comment by CostasAthan** [comment]
I'm afraid not...

I have followed the instructions found  here: [https://github.com/TobiasBuchholz/Plugin.Firebase/blob/master/README.md#basic-setup](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/master/README.md#basic-setup), with no success.

**Comment by AdamEssenmacher** [comment]
So you are definitely calling `FirebaseAnalyticsImplementation.Initialize(activity)`?

**Comment by CostasAthan** [comment]
Yes, I have called it!

I have also copied the code from the link I shared and have added it in **MauiProgram.cs**.

I just used break points to make sure that `CrossFirebase.Initialize(activity);` in **MauiProgram.cs** is called before `FirebaseAnalyticsImplementation.Initialize(this);` in **MainActivity.cs**.

Here is the respective code from **MauiProgram.cs**:

```
        private static MauiAppBuilder RegisterFirebaseServices(this MauiAppBuilder builder)
        {
            builder.ConfigureLifecycleEvents(events => {
#if IOS
            events.AddiOS(iOS => iOS.WillFinishLaunching((_,__) => {
                CrossFirebase.Initialize();
                return false;
            }));
#elif ANDROID
                events.AddAndroid(android => android.OnCreate((activity, _) =>
                    CrossFirebase.Initialize(activity)));
#endif
            });

            builder.Services.AddSingleton(_ => CrossFirebaseAuth.Current);
            builder.Services.AddSingleton(_ => CrossFirebaseAnalytics.Current);
            return builder;
        }
```

and here you can see the respective code from **MainActivity.cs**:

```
        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            MobileAds.Initialize(this);
            FirebaseAnalyticsImplementation.Initialize(this);
            SetGDPR();
        }
```

As I said using brake points I can see that `CrossFirebase.Initialize(activity)));` in the Android preprocessor in **MauiProgram.cs** is reached first, before the `FirebaseAnalyticsImplementation.Initialize(this);` statement in **MainActivity.cs** gets executed.

But now I have to ask: When the following code gets executed:

```
#elif ANDROID
                events.AddAndroid(android => android.OnCreate((activity, _) =>
                    CrossFirebase.Initialize(activity)));
#endif
```

does the `CrossFirebase.Initialize(activity)));` line really gets executed or does it get injected in the end of the `OnCreate` method **and thus it actually gets executed after** the `FirebaseAnalyticsImplementation.Initialize(this);` statement?

**Comment by AdamEssenmacher** [comment]
It sounds like you're calling

`CrossFirebaseAnalytics.Current.IsAnalyticsCollectionEnabled = true;`

before

`FirebaseAnalyticsImplementation.Initialize(this);`

The initialize call has to come first.

**Comment by CostasAthan** [comment]
I should add that I had installed the [Plugin.Firebase](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/docs/bundled.md) package. Initially I thought that this was causing the issue. But what I found out is that I hadn't set the **google-services.json** build action to **GoogleServicesJson**. I think that was all. Anyway, now I can run the app, regardless if I use **Plugin.Firebase** or just a couple of the specific Plugins I need instead.

I have one question though. Do I have to set `CrossFirebaseAnalytics.Current.IsAnalyticsCollectionEnabled` either as `true` or `false` in every `Page` of the app or does this have to happen in one specific file?

**Comment by AdamEssenmacher** [comment]
Closing the issue as it's gone off topic and the original question appears to be answered.

@CostasAthan you're at the point where you should just be referring to the native SDK documentation (this plugin is just a thin wrapper)

e.g. https://firebase.google.com/docs/analytics/configure-data-collection?platform=android
