### ISSUE TITLE
Error  : clang++ exited with code 1 on Maui .Net8

### ISSUE THREAD

**Issue by mfranc28** [TobiasBuchholz/Plugin.Firebase#322]
With Maui .net 8 having this issue when compiling

0>Xamarin.Shared.Sdk.targets(1564,3): Error  : clang++ exited with code 1:
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility50'
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
ld: warning: Could not find or use auto-linked library 'swiftOSLog'
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftCompatibilityDynamicReplacements'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftCompatibility51'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
ld: warning: Could not find or use auto-linked library 'swiftUIKit'
ld: warning: Could not find or use auto-linked library 'swif
0>------- Finished building project: CareMapMobile. Succeeded: False. Errors: 1. Warnings: 3152

I follow all the step and using last version of Plugin.Firebase Nuget package (3.0.0)

**Comment by agaluzzi** [comment]
@mfranc28 I was struggling with the same issue, but these instructions from @AdamEssenmacher have resolved it: https://github.com/AdamEssenmacher/GoogleApisForiOSComponents?tab=readme-ov-file#firebase-analytics
