### ISSUE TITLE
FCM update 2.0.4 -> 3.0.0

### ISSUE THREAD

**Issue by axylophon** [TobiasBuchholz/Plugin.Firebase#329]
Hi,

I have a question regarding the FCM nuget update (2.0.4 -> 3.0.0) which I could not resolve with the documentation.

As I understand with 3.0.0 the dependency for iOS was updated to the community version as it is not maintained by Microsoft anymore.

Does the older version 2.0.4 use the legacy FCM API which is already killed by Google? Or is the older version currently still working in production and not affected of the API shutdown? Could anybody please provider more information regarding that topic?

King Regards
Alex

**Comment by AdamEssenmacher** [comment]
Versions of this plugin < 3.0.0 used the Xamarin.Firebase.iOS.* packages, which were never updated past native SDK versions 8.10. As of June, Google recommended a minimum FCM SDK version of 10.0, so I wouldn't be surprised if anything older doesn't work in production now.

There's also the issue of privacy manifest support.

Bottom line is that any version of this plugin < 3.0.0 probably shouldn't be used in production.
