### ISSUE TITLE
Plugin.Firebase is not available in .net8-ios

### ISSUE THREAD

**Issue by EminNiftili** [TobiasBuchholz/Plugin.Firebase#331]
Create new project.
`dotnet new maui -n MyMauiApp`

Install Plugin.Firebase
`dotnet add package Plugin.Firebase --version 3.0.0`

Then add `using`  into `MauiProgram.cs`.
`using Plugin.Firebase.Auth;`

Idea show warning 'this package is not available, net8-ios'

![image](https://github.com/user-attachments/assets/568e96a6-1cdf-4328-851a-6a78c9537187)

My dependency like that!
![image](https://github.com/user-attachments/assets/1a69abfe-0500-4716-94b9-3622dc422d54)

**Comment by AdamEssenmacher** [comment]
Looks like you're on Windows/Visual Studio? First guess is you're running into https://github.com/TobiasBuchholz/Plugin.Firebase?tab=readme-ov-file#windows-11-long-path-issue
