### ISSUE TITLE
Firestore - SetDataAsync doesn't write data, no errors

### ISSUE THREAD

**Issue by rezamohamed** [TobiasBuchholz/Plugin.Firebase#343]
The SetDataAsync doesn't seem to write any data. It creates the collection and the document, but the fields are empty. No Exceptions or errors are thrown, I get a data successfully written message:

```
        var data = new Dictionary<string, object>
        {
            { "StartingTab", 12345 } // Explicit integer value
        };

        try
        {
            await CrossFirebaseFirestore.Current
                .GetCollection("Users")
                .GetDocument("Testing")
                .SetDataAsync(data)
                .ContinueWith(task =>
                {
                    if (task.IsCompletedSuccessfully)
                    {
                        Console.WriteLine("Data successfully written!");
                    }
                    else
                    {
                        Console.WriteLine("Error writing data: " + task.Exception?.Message);
                    }
                });
        }
        catch (Exception e)
        {
            Console.WriteLine(e);
            throw;
        }
```

![CleanShot 2024-09-26 at 16 57 59@2x](https://github.com/user-attachments/assets/2e91c02c-88f5-448d-9b1d-3290b7481b43)

**Comment by rezamohamed** [comment]
I did it differently, and don't need the code as shown here, so closing for now.

**Comment by mihaimyh** [comment]
What was the problem, I am seeing the same issue.

**Comment by rezamohamed** [comment]
If I remember correctly, the way I had written that code was incorrect. I did it like this and it worked:

var data = new Dictionary<object, object>
        {
            { "StartingPage", doc.StartingPage },
            { "OrderBy", doc.OrderBy } // Explicit integer value
        };

        await firestore
            .GetCollection(RootUserCollectionName)
            .GetDocument(user.UserId)
            .SetDataAsync(data, SetOptions.Merge());
    }
