### ISSUE TITLE
Xamarin.Firebase.Firestore 125.0.0 - System.TypeLoadException: expected class 'Firebase.Timestamp' in assembly 'Xamarin.Firebase.Firestore'

### ISSUE THREAD

**Issue by tranb3r** [TobiasBuchholz/Plugin.Firebase#344]
When updating `Xamarin.Firebase.Firestore` to 125.0.0, I get the following exception when retrieving a document from firestore:
```
System.TypeLoadException: Could not resolve type with token 0100007a from typeref (expected class 'Firebase.Timestamp' in assembly 'Xamarin.Firebase.Firestore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null')
    at Plugin.Firebase.Firestore.Platforms.Android.Extensions.JavaObjectExtensions.Cast[FirestoreDocument](IDictionary`2 this, String documentId)
```

Maybe it's time to update the plugin's dependencies, and then fix this issue.
What do you think?

**Comment by AdamEssenmacher** [comment]
Thanks for the report @tranb3r. A PR would be welcome :)

**Comment by tranb3r** [comment]
To be honest, I have no idea how to test the whole plugin and make sure nothing is broken when upgrading dependencies.

**Comment by AdamEssenmacher** [comment]
> To be honest, I have no idea how to test the whole plugin and make sure nothing is broken when upgrading dependencies.

I think @TobiasBuchholz runs the included set of tests before each release? He could confirm.

That said, you probably wouldn't need to update this plugin's **minimum** dependencies to contribute a fix. The [release notes for Cloud Firestore 25.0.0](https://firebase.google.com/support/release-notes/android#firestore_v25-0-0) show no breaking API changes, but it looks like a (supposed to be non-breaking) [feature](https://github.com/firebase/firebase-android-sdk/pull/5853) was added related to Timestamps, which I'd bet is the root cause of our issue here. I have a hunch that `JavaObjectExtensions` could be updated in such a way that this plugin continues to function correctly for version < 125.x.x, while also working for versions >125.x.x.

**Comment by tranb3r** [comment]
@AdamEssenmacher 
In `JavaObjectExtensions`, it's expecting to find `Firebase.Timestamp` in `Xamarin.Firebase.Firestore`. Unfortunately, it's been moved to `Xamarin.Firebase.Common` in a more recent version. Hence the `TypeLoadException`.
I really don't see how this could work without updating the `Xamarin.Firebase.Firestore` minimum version referenced by the plugin.

**Comment by tranb3r** [comment]
@AdamEssenmacher @TobiasBuchholz Any advice on how to fix this issue?

**Comment by AdamEssenmacher** [comment]
Pulling the plugin's minimum dependencies forward is certainly an option.

I wonder if [type forwarding](https://learn.microsoft.com/en-us/dotnet/standard/assembly/type-forwarding) could work in this case?

**Comment by tranb3r** [comment]
Type forwarding could work if we were to modify xamarin.firebase.firestore. But that's not really an option.
I can upgrade min dependencies for `Xamarin.Firebase.Firestore` and `Xamarin.Firebase.Common`.
The questions are: how to test this kind of upgrade? And do we need to upgrade the other packages?

**Comment by AdamEssenmacher** [comment]
> But that's not really an option
It might be. Maybe the Microsoft team would accept a PR? Idk.

> how to test this kind of upgrade?
We do our best to exercise the code with a sample app. In this case, I'd say that if we see timestamps working after an update, it's probably fine. Then we do the scream test.

> And do we need to upgrade the other packages
Probably not. Just let nuget do its job and resolve the needed package versions for a given project.

**Comment by tranb3r** [comment]
> Maybe the Microsoft team would accept a PR? Idk.

Good luck with that.
Also, I'm not sure it's worth it.

> Just let nuget do its job and resolve the needed package versions for a given project.

I've prepared a PR, simply updating xamarin.firebase.firestore version.
