### ISSUE TITLE
Is it possible to turn off persistence temporarily?

### ISSUE THREAD

**Issue by cagriy** [TobiasBuchholz/Plugin.Firebase#349]
My app normally uses persistence. However, there is one occasion where I have to make sure I am actually getting the latest information available in a collection.

Due to persistence, GetDocumentsAsync simply completes with some stale data in it if the internet is not available or the listener has not been triggered.

I'd like to make GetDocumentsAsync wait until it actually gets the data from the Firestore. What is the best way to achieve this?

I understand it is not possible to set CrossFirebaseFirestore.Current.Settings on the fly.

Is there any solution other than turning off persistence altogether?

Many thanks

**Comment by AdamEssenmacher** [comment]
https://firebase.google.com/docs/firestore/query-data/get-data#source_options

**Comment by cagriy** [comment]
Thank you @AdamEssenmacher
