### ISSUE TITLE
PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by IgleDev** [TobiasBuchholz/Plugin.Firebase#353]
When i try to install Plugin.Firebase, this don't let me install, it say "Cannot find a part of the path 'PrivacyInfo.xcprivacy". I'm so confusing rn

**Comment by AdamEssenmacher** [comment]
Sounds like the long path issue

**Comment by IgleDev** [comment]
yeah i know! But what??

**Comment by AndrzejKozik** [comment]
Once you enable long paths in Windows, the project location doesn't matter (at least for me). Modify csproj (add necessary references), and then, in CMD, nav. to solution folder and run dotnet build - it does the job - You could then build from VS.
