### ISSUE TITLE
Using Plugin.Firebase.CloudMessaging on Xamarin (not MAUI)?

### ISSUE THREAD

**Issue by bitshftr** [TobiasBuchholz/Plugin.Firebase#355]
I want to use Plugin.Firebase.CloudMessaging, but my app is Xamarin (not MAUI) and I get package installer errors about .net6.  I tried Plugin.Firebase.Legacy 1.1.5 but I get this error:
`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Shawn.Lipscomb\.nuget\packages\xamarin.facebook.sharekit.ios\12.2.0\lib\xamarinios10\Facebook.ShareKit.resources\FBSDKShareKit.xcframework\ios-arm64_i386_x86_64-simulator\FBSDKShareKit.framework\Modules\FBSDKShareKit.swiftmodule\arm64-apple-ios-simulator.swiftdoc'.`

Is there any way I can use either of these packages?

**Comment by AdamEssenmacher** [comment]
First, the error you're seeing looks like the long path issue. That's a completely separate problem.

Even if you worked through the long path issue, the legacy package uses Microsoft's deprecated Xamarin.Firebase.iOS.* packages that don't have the privacy manifest stuff.

Your best path forward would be to fork the legacy branch and migrate the iOS side to use the AdamE.Firebase.iOS.* packages.

Xamarin apps won't be deployable to the App Store probably in April, so I'm not sure how much value you'd get out of this effort before upgrading away from Xamarin is your only option.
