### ISSUE TITLE
Firestore Query WhereEqualsTo null ?

### ISSUE THREAD

**Issue by barrysohl** [TobiasBuchholz/Plugin.Firebase#359]
In the past, with Xamarin and Plugin.Firestore we were able to run queries and check for null values with LINQ like so: `ICollectionReference.WhereEqualsTo( "someproperty", null )
`

But with Plugin.Firebase.Firestore on MAUI, this throws a NullReferenceException (see below). Is there some other way to query for fields that have null values? Thanks in advance.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Plugin.Firebase.Firestore.Platforms.iOS.Extensions.NSObjectExtensions.ToNSObject(Object this)
   at Plugin.Firebase.Firestore.Platforms.iOS.QueryWrapper.WhereEqualsTo(String field, Object value)
```

**Comment by AdamEssenmacher** [comment]
It looks like the current implementation just missed this case. I don't think there's a workaround, but the linked PR should fix it.

**Comment by barrysohl** [comment]
Thanks for the quick 3.1.1 push. I can confirm that this issue is now fixed in our production project.
