### ISSUE TITLE
Could not find a part of the path 

### ISSUE THREAD

**Issue by ameralfaqeeh86** [TobiasBuchholz/Plugin.Firebase#360]
Hi, I tried all the solutions to solve the error below when I was trying to install the plugin.Firebase 3.0.0 or any version.

Please, I need to launch the application to live ASAP

**Could not find a part of the path** 'C:\Nuget\xamarin.facebook.gamingserviceskit.ios\12.2.0.1\lib\net6.0-ios15.4\Xamarin.Facebook.GamingServicesKit.resources\FBSDKGamingServicesKit.xcframework\ios-arm64_armv7\FBSDKGamingServicesKit.framework\Modules\FBSDKGamingServicesKit.swiftmodule\armv7-apple-ios.swiftdoc'.

**Could not find a part of the path** 'C:\Nuget\adame.firebase.ios.core\10.24.0\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.	

Thank you.

**Comment by AdamEssenmacher** [comment]
https://github.com/AdamEssenmacher/GoogleApisForiOSComponents?tab=readme-ov-file#windows--visual-studio-long-path-issue
