### ISSUE TITLE
iOS Release deployment with .NET 9.0. Could not find the type 'ObjCRuntime.__Registrar__'

### ISSUE THREAD

**Issue by kaniosm** [TobiasBuchholz/Plugin.Firebase#372]
I'm getting the below error in deployment after upgrading to .NET 9.0.

Could not find the type 'ObjCRuntime.__Registrar__' in the assembly 'Firebase.CloudFunctions'.

Any thoughts?

Thx

**Comment by AdamEssenmacher** [comment]
https://github.com/xamarin/xamarin-macios/wiki/.NET-9-release-notes#type-registrar-managed-static-as-the-new-default

**Comment by kaniosm** [comment]
Thanks for the link @AdamEssenmacher.
In my case I believe this was caused by trimming. I was not really using CloudFunctions, but had a reference to the library in my push notifications service. After I removed the reference and the NuGet package all works as expected.

**Comment by natevarghese** [comment]
Please use this as a test repo. It has the objc bindings already so it's quite large but not a lot of code is required to reproduce it.
https://github.com/natevarghese/Solution1

As a reminder it only crashes on physical iOS devices, so you will need to update the bundle identifier to one you have provisioned.

**Comment by natevarghese** [comment]
Please look here. A similar issue however, the instructions in the link only made it worse.

https://github.com/dotnet/maui/issues/27312

**Comment by AdamEssenmacher** [comment]
> the instructions in the link only made it worse.

Or perhaps it moved you along to a separate, unrelated problem.
