### ISSUE TITLE
Firestore retrieval errors only on Android

### ISSUE THREAD

**Issue by cagriy** [TobiasBuchholz/Plugin.Firebase#374]
Can I please check if I am missing something?

The MAUI app I am developing interacts with Firestore with no issues using this plugin (2.0.7 or 3.0.x, .NET 8)
When I try to retrieve a record on Android using GetDocumentsAsync<MyType> I get following exception:
```
System.ArgumentOutOfRangeException: Not a valid Win32 FileTime. (Parameter 'fileTime')
   at System.DateTime.FromFileTimeUtc(Int64 fileTime)
   at Plugin.Firebase.Firestore.Platforms.Android.Extensions.DateExtensions.ToDateTime(Date date)
```

This is consistent on all three versions I tried, and iOS works just fine. I confirmed that the Firestore document is retrieved and this error occurs when it is cast back to the object I am using. Although I get mostly this issue with what looks like a DateTime conversion, on one other occasion it was complaining about covering "2" to Int32 (although the field was stored as a number in Firestore.

For all three versions I tested, I updated dependencies as per the Readme.

I appreciate any ideas you can suggest to solve or further troubleshoot the issue.

**Comment by AdamEssenmacher** [comment]
Can you provide a sample of a [IFirestoreObject DTO ](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/docs/firestore.md#usage) that causes the issue?

Also, more of the stack trace might be helpful.

**Comment by cagriy** [comment]
Thanks @AdamEssenmacher , both are attached.
[Model.txt](https://github.com/user-attachments/files/17828224/Model.txt)
[stacktrace.txt](https://github.com/user-attachments/files/17828230/stacktrace.txt)

**Comment by AdamEssenmacher** [comment]
Your model doesn't implement IFirestoreObject.

Also please try using DateTimeOffset.

**Comment by cagriy** [comment]
@AdamEssenmacher, thanks for your help.
The issues were indeed due to using DateTime instead of DateTimeOffset. Other problems seemed to be due to corrupt records being written back into the database.
