### ISSUE TITLE
Could not find a part of the path

### ISSUE THREAD

**Issue by suariana** [TobiasBuchholz/Plugin.Firebase#378]
Hi, i got this error when trying to install this packages

Could not find a part of the path 'C:\Nuget\adame.firebase.ios.core\10.24.0\lib\net6.0-ios16.1\Firebase.Core.resources\FirebaseCoreInternal.xcframework\ios-arm64_x86_64-simulator\FirebaseCoreInternal.framework\Modules\FirebaseCoreInternal.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.

how to resolve this error?
thanks

**Comment by marcelojaf** [comment]
I believe you are using Windows, correct?

Take a look at this: https://github.com/TobiasBuchholz/Plugin.Firebase?tab=readme-ov-file#troubleshooting
