### ISSUE TITLE
fcmToken problem on iOS when change Xamarin.Firebase.iOS.CloudMessaging into Plugin.Firebase

### ISSUE THREAD

**Issue by suariana** [TobiasBuchholz/Plugin.Firebase#386]
Hello, i have problem when trying to change old Xamarin.Firebase.iOS.CloudMessaging and Xamarin.Firebase.Messaging (on Android) to Plugin.Firebase

My project using dotnet 8 and MauiVersion 8.0.92
the problem is when i run this code below on iOS, the token that i receive is the last generated token from old Xamarin.Firebase.iOS.CloudMessaging. 
Then when trying to send notification to iOS device, the result is not found
the library is works greats on Android, but the problem just in iOS device
when i run the project using old Xamarin.Firebase.iOS.CloudMessaging, the token in iOS is changing when i uninstall and install the application, but the notification is not showing even when the app is open or closed so i want to change the lib to Plugin.Firebase
may i know how to resolve this problem?
thankyou :)

 ```
private void Configure()
 {
     //Firebase.Core.App.Configure();

     CrossFirebase.Initialize();
     FirebaseCloudMessagingImplementation.Initialize();

     if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
     {
         var authOption = UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound;

         UNUserNotificationCenter.Current.RequestAuthorization(authOption, (granted, error) =>
         {
             Console.WriteLine($"Registration is success: {granted}");

             if (error != null)
             {
                 Console.WriteLine($"Registration for push notifications error: {error.DebugDescription}");
             }

             if (granted && error == null)
             {
                 this.InvokeOnMainThread(() =>
                 {
                     UIApplication.SharedApplication.RegisterForRemoteNotifications();

                     CrossFirebaseCloudMessaging.Current.TokenChanged += Current_TokenChanged;

                     this.RegisterNotification();
                 });
             }
         });


     }


 }

 private void Current_TokenChanged(object sender, Plugin.Firebase.CloudMessaging.EventArgs.FCMTokenChangedEventArgs e)
 {
     FirebaseNotification.Current.InvokeTokenRefresh(e.Token);
 }

 private async void GenerateNewToken()
 {
     await CrossFirebaseCloudMessaging.Current.CheckIfValidAsync();
     var token = await CrossFirebaseCloudMessaging.Current.GetTokenAsync();
     FirebaseNotification.Current.InvokeTokenRefresh(token);
 }

 private void RegisterNotification()
 {
     UNUserNotificationCenter.Current.Delegate = new Platforms.iOS.UserNotificationCenterDelegate();
     Messaging.SharedInstance.AutoInitEnabled = true;
     Messaging.SharedInstance.Delegate = this;
     //GetToken();
     GenerateNewToken();
 }
```

**Comment by AdamEssenmacher** [comment]
What does your Info.plist look like?

**Comment by suariana** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>arm64</string>
	</array>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleLocalizations</key>
	<array>
		<string>en</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>XSAppIconAssets</key>
	<string>Assets.xcassets/appicon.appiconset</string>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
	<key>NSCameraUsageDescription</key>
	<string>Aplikasi memerlukan akses kekamera untuk mengambil gambar atau scan barcode.</string>
	<key>NSPhotoLibraryUsageDescription</key>
	<string>Aplikasi memerlukan akses galery untuk menambahkan gambar pada item.</string>
	<key>NSPhotoLibraryAddUsageDescription</key>
	<string>Aplikasi memerlukan akses galery untuk menambahkan gambar pada item.</string>
	<key>NSBluetoothPeripheralUsageDescription</key>
	<string>Aplikasi memerlukan akses ke Bluetooth untuk koneksi ke printer.</string>
	<key>NSBluetoothAlwaysUsageDescription</key>
	<string>Aplikasi memerlukan akses ke Bluetooth untuk koneksi ke printer.</string>
	<key>NSContactsUsageDescription</key>
	<string>Aplikasi memerlukan akses ke kontak untuk mengirim pesan atau bukti laporan</string>
	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>whatsapp</string>
	</array>
	<key>UIRequiresFullScreen</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>bluetooth-central</string>
		<string>bluetooth-peripheral</string>
		<string>fetch</string>
		<string>remote-notification</string>
	</array>
	<key>CFBundleShortVersionString</key>
	<string>1.25.13</string>
	<key>CFBundleIdentifier</key>
	<string>com.yana.tesnotifikasi</string>
	<key>MinimumOSVersion</key>
	<string>11.0</string>
	<key>CFBundleDisplayName</key>
	<string>Tes Notifikasi</string>
	<key>UIAppFonts</key>
	<array>
		<string>Assistant-Regular.ttf</string>
		<string>Assistant-Bold.ttf</string>
		<string>SegMDL2.ttf</string>
		<string>Ubuntu-Regular.ttf</string>
		<string>Ubuntu-Medium.ttf</string>
		<string>Dosis-Regular.ttf</string>
		<string>Dosis-Bold.ttf</string>
		<string>CherrySwash-Regular.ttf</string>
		<string>CherrySwash-Bold.ttf</string>
		<string>CaveatBrush-Regular.ttf</string>
		<string>BubblegumSans-Regular.ttf</string>
	</array>
	<key>CFBundleVersion</key>
	<string>14</string>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>CFBundleURLName</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.google.fcm</string>
			</array>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
		</dict>
	</array>
</dict>
</plist>

**Comment by suariana** [comment]
i already delete this from my info.plist

```
<key>FirebaseAppDelegateProxyEnabled</key>
<false/>
<array>
<dict>
	<key>CFBundleURLName</key>
	<string>CFBundleURLName</string>
	<key>CFBundleURLSchemes</key>
	<array>
		<string>com.google.fcm</string>
	</array>
	<key>CFBundleTypeRole</key>
	<string>Editor</string>
</dict>
</array>
```
but when i run this code below, i got new error 
Error Domain=com.google.fcm Code=505 "No APNS token specified before fetching FCM Token" UserInfo={NSLocalizedFailureReason=No APNS token specified before fetching FCM Token}

```
await CrossFirebaseCloudMessaging.Current.CheckIfValidAsync();
var token = await CrossFirebaseCloudMessaging.Current.GetTokenAsync();
```

i need an help, thankyou

**Comment by suariana** [comment]
fixed by i dont know when i receive this error the notification is viewing on ios
Error Domain=com.google.fcm Code=505 "No APNS token specified before fetching FCM Token" UserInfo={NSLocalizedFailureReason=No APNS token specified before fetching FCM Token}
