### ISSUE TITLE
Issue with Firebase Initialization in MAUI Android and iOS Projects

### ISSUE THREAD

**Issue by IX-OmkarP** [TobiasBuchholz/Plugin.Firebase#390]
Hello,

I am encountering an issue with initializing Firebase in my MAUI Android and iOS projects. Specifically, I am seeing the following error on Android:

```
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: 
Java.Lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.companyname.crossfirebasefirebasecrashlytics. 
Make sure to call FirebaseApp.initializeApp(Context) first.
```

On iOS, I am encountering a similar issue where the default Firebase app is not initialized.

**Steps Taken:**
 - I have confirmed that both the google-services.json (Android) and GoogleService-Info.plist (iOS) files are in the correct locations and have the correct build actions set.
- I have also added the necessary Firebase dependencies to my project.
- The package name in google-services.json matches the one in AndroidManifest.xml.

Despite these efforts, the error persists on both platforms. Could anyone help me identify what might be causing this issue or suggest any additional steps I should take to resolve it?

For reference, you can find my project on GitHub here: [CrossFirebaseFirebaseCrashlytics](https://github.com/IX-OmkarP/CrossFirebaseFirebaseCrashlytics).

**Comment by AdamEssenmacher** [comment]
Your build action isn't set right.

https://github.com/TobiasBuchholz/Plugin.Firebase/blob/a9f5ae1da58b8938b4538dd54a867278cc73c2ff/sample/Playground/Playground.csproj#L95

**Comment by IX-OmkarP** [comment]
Hello,

Thank you for your response. I checked the build actions:

**Android (google-services.json):**
- After this correction, Firebase is now working on Android.

**iOS (GoogleService-Info.plist):**
- The file is in the correct location and set to BundleResource, but I still get a null reference issue, and the default Firebase app is not initialized.

Could you guide me on what else to check or configure for iOS?

Thank you!

**Comment by AdamEssenmacher** [comment]
`CrossFirebase.Initialize(settings)` needs to be called before trying to access `CrossFirebaseCrashlytics.Current`

https://github.com/TobiasBuchholz/Plugin.Firebase/blob/development/docs/crashlytics.md#setup

**Comment by IX-OmkarP** [comment]
@AdamEssenmacher Thank you for the advice! Calling CrossFirebase.Initialize(settings) before accessing CrossFirebaseCrashlytics.Current resolved the issue on both Android and iOS.

I appreciate your help and the documentation reference!

Thanks again!
