### ISSUE TITLE
Plugin.CurrentActivity dependency

### ISSUE THREAD

**Issue by tranb3r** [TobiasBuchholz/Plugin.Firebase#44]
This plugin depends both on Plugin.CurrentActivity and Xamarin.Essentials.
The 'CurrentActivity' functionality is available is Xamarin.Essentials.
So I think you could easily get rid of the Plugin.CurrentActivity dependency.
Or is there a reason to keep it? What do you think?

**Comment by TobiasBuchholz** [comment]
Yes you are right, this dependency could actually be removed. Unfortunately for some reason the `Xamarin.Essentials.Platform` namespace can't be resolved in the android `FirebaseAuthImplementation` class, see screenshot.

![screenshot](https://user-images.githubusercontent.com/1132836/177137519-273fd9f8-ad4f-49d9-ac12-3e9f1ba259e8.jpg)

I will keep an eye on it though.

**Comment by TobiasBuchholz** [comment]
With version 1.2.0 the depency to `Plugin.CurrentActivity` is now removed.
