### ISSUE TITLE
.NET MAUI

### ISSUE THREAD

**Issue by angelru** [TobiasBuchholz/Plugin.Firebase#48]
Is your library compatible with .NET MAUI?

**Comment by angelru** [comment]
I don't know how to solve it either

**Comment by TobiasBuchholz** [comment]
The new version 1.2.0 now supports .NET MAUI applications! 🚀 Take a look at [section .NET MAUI support](https://github.com/TobiasBuchholz/Plugin.Firebase#net-maui-support) in the README for more information.
