### ISSUE TITLE
Exception: iOS @NSError.userInfo

### ISSUE THREAD

**Issue by sattasundar** [TobiasBuchholz/Plugin.Firebase#5]
After enter the OTP and click on verify I am getting below error;

*An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered*

Platform: iOS
Device: iPhone SE simulator(14.4)
![Simulator Screen Shot - iPhone SE (2nd generation) - 2021-02-17 at 12 55 31](https://user-images.githubusercontent.com/62828724/108170186-d1a35800-711f-11eb-970d-e94a20d7c2cd.png)

- Entitlement.plist

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)com.xamarin.auth</string>
	</array>
</dict>
</plist>
```

- Info.plist

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>UIDeviceFamily</key>
	<array>
		<integer>1</integer>
		<integer>2</integer>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>MinimumOSVersion</key>
	<string>8.0</string>
	<key>CFBundleDisplayName</key>
	<string>XamDemo</string>
	<key>CFBundleIdentifier</key>
	<string>com.xamarin.auth</string>
	<key>CFBundleVersion</key>
	<string>1.0</string>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>CFBundleName</key>
	<string>XamDemo</string>
	<key>XSAppIconAssets</key>
	<string>Assets.xcassets/AppIcon.appiconset</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.479574513872-58k1codlmhfl3j0v3m5tiembubiltb46</string>
			</array>
		</dict>
	</array>
</dict>
</plist>
```

**Comment by TobiasBuchholz** [comment]
This might be a [problem with the simulator](https://stackoverflow.com/a/39653486/1525503). Did you try it on a real device?

**Comment by sattasundar** [comment]
Okay, will try on real device.

**Comment by Kapusch** [comment]
Hi @TobiasBuchholz , I have discovered your library very recently and that's really neat having such a wrapper for all the different Firebase services, thank you ! 

To answer your question, yes it works on a device. Only on Simulator it throws this KeyChain Access error.

My solution so that it works on Simulator too @sattasundar : 
1. Enable Keychain in your Entitlements.plist file for your iOS project
2. In your iOS project, go to iOS Bundle Signing and set Entitlements.plist in Custom Entitlements field

I let you give a try but I think you can mark the issue as resolved.
