### ISSUE TITLE
Question: Support for custom claims

### ISSUE THREAD

**Issue by 420tech** [TobiasBuchholz/Plugin.Firebase#50]
This is more of a question than a bug. Does this library support retrieving custom claims for the authenticated user?

**Comment by TobiasBuchholz** [comment]
Nope, not yet, but it seems to be easy to add, so it will be in there in the next version.

**Comment by TobiasBuchholz** [comment]
The current version 1.1.2 now supports custom claims for user authentication. You can take a look at the following links to get more information.

https://github.com/TobiasBuchholz/Plugin.Firebase/blob/d4d4b0ca175ceb28fcc5b5d4e42b098ea31abbf7/src/Shared/Auth/IFirebaseUser.cs#L64

https://github.com/TobiasBuchholz/Plugin.Firebase/blob/d4d4b0ca175ceb28fcc5b5d4e42b098ea31abbf7/src/Shared/Auth/IAuthTokenResult.cs#L29

https://github.com/TobiasBuchholz/Plugin.Firebase/blob/d4d4b0ca175ceb28fcc5b5d4e42b098ea31abbf7/tests/Plugin.Firebase.IntegrationTests/Auth/AuthFixture.cs#L143
