### ISSUE TITLE
Package does not install on iOS project

### ISSUE THREAD

**Issue by 420tech** [TobiasBuchholz/Plugin.Firebase#51]
Using Visual Studio 2022 (repos both on Windows and Mac).

File->New Project. Choose Tabbed template. Compiles and builds.
Add Plug.Firebase to Shared Project, Android and iOS. Package fails to install on iOS with this error Install-Package : Could not find a part of the path 'C:\Users\timbe\.nuget\packages\xamarin.facebook.sharekit.ios\12.2.0\lib\xamarinios10\Facebook.ShareKit.resources\FBSDKShareKit.xcframework\ios-arm64_i386_x86_64
-simulator\FBSDKShareKit.framework\Modules\FBSDKShareKit.swiftmodule\arm64-apple-ios-simulator.swiftdoc'.

Only other libraries already install are Xamarin.Forms and Xamarin.Essentials.

I tried clearing the nuget cache - same results.
I tried adding Xamarin.Facebook.ios and got same results.

**Comment by mrtcn** [comment]
I am having the same issue. @420tech  Did you find a solution to it?
I have installed the package on my vs for mac successfully and pulled the changes on my windows machine however the package is somehow not recognized on windows. It seems to be installed on nuget package manager but in the code I get the following errors;
`The type or namespace name 'Firebase' does not exist in the namespace 'Plugin' (are you missing an assembly reference?)	Tibi.Forms.iOS`
`The type or namespace name 'CrossFirebaseSettings' could not be found (are you missing a using directive or an assembly reference?)	Tibi.Forms.iOS`

**Comment by migueBarrera** [comment]
@420tech i have same issue after update to net 7 my project

**Comment by faceoffers28** [comment]
I finally got my project to build by doing this. 

1) Install version 1.2.1 of the plugin using the Nuget Package Manager console. The dependency versions are too high for v 1.2.2.

dotnet add package Plugin.Firebase -v 1.2.

2) I changed the following in cs.proj to the exact TargetFramework version. Notice the 31.0 and 15.4.

```
<!--Added for Plugin.Firebase--> 
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android31.0'">
    <GoogleServicesJson Include="google-services.json" />
	</ItemGroup>

  <!--Added for Plugin.Firebase-->
	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-ios15.4'">
    <BundleResource Include="GoogleService-Info.plist" />
	</ItemGroup>
  
  <!--Added to fix Android build errors with Plugin.Firebase--> 
  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0-android31.0'">
		<PackageReference Include="Xamarin.Kotlin.StdLib.Jdk7" Version="1.7.10" ExcludeAssets="build;buildTransitive" />
		<PackageReference Include="Xamarin.Kotlin.StdLib.Jdk8" Version="1.7.10" ExcludeAssets="build;buildTransitive" />
	</ItemGroup>
```

**Comment by faceoffers28** [comment]
@420tech Did that work for you?

**Comment by 420tech** [comment]
Yes! Thank you!
