### ISSUE TITLE
CloudMessaging:  CrossFirebaseCloudMessaging.Current.NotificationTapped not invoked when app is killed

### ISSUE THREAD

**Issue by Mataboge** [TobiasBuchholz/Plugin.Firebase#59]
The `CrossFirebaseCloudMessaging.Current.NotificationTapped` method is invoked when a user taps on a notification which was received when an app is in the background, in this case the method works. The Foreground method of receiving notifications also works perfect.

The issue comes when a user kills an app (by sliding up on both Android & iOS), and later receivers a notification: The notification pops up normally on the system tray, when a user taps on it, the app opens but the method `CrossFirebaseCloudMessaging.Current.NotificationTapped`  is not fired. This happens on both platforms [android & iOS]

This is where I am initializing this method on the shared project, all the platform specific code were followed as per instructions 

        public App()
        {
            CrossFirebaseCloudMessaging.Current.NotificationTapped += Current_NotificationTapped;
            ....
        }

**Comment by Mataboge** [comment]
It turns out the method is being called correctly, the issue was in my implementation where the method is being called before my custom initialisation has completed. Was a bit harder debugging an app in a dead-state.

**Comment by TobiasBuchholz** [comment]
Sorry for not responding earlier but I'm glad you were able to resolve this issue! :)

**Comment by anilrawatGH** [comment]
Hello @Mataboge 

Can you please share your code that how you are receiving the Notification and able to hit the NotificationTapped method when app is killed?

I am able to receive the Notification on Foreground and Background but not receiving the notification when app is killed.

Is there any extra setting which I need to configure for receiving the notification in killed app?

**Comment by leohh** [comment]
I have the same issue with tapping but wit .net Maui.

Eveereything works, but only when the app is in foreground Body and Titel is displayed (and saved to sqllite)
in backgruond and/or killed the app opens,  navigates to the right position.. I can see everything except body and title... 

Any thoughts ?? 


![image](https://github.com/TobiasBuchholz/Plugin.Firebase/assets/2938551/892ca9dc-7d70-47dc-9dcc-69dd4afc0631)

**Comment by huzaifa-saeed** [comment]
Any update regarding this issue?
CrossFirebaseCloudMessaging.Current.NotificationTapped not invoked when app is killed.
