### ISSUE TITLE
Android Download crash

### ISSUE THREAD

**Issue by geogian98** [TobiasBuchholz/Plugin.Firebase#6]
Hi!I like your plugin and thanks for it. I tryed to download a file in my project and there it seems to be a problem.
I also tryed in your sample project and the problem is still there.
I tryed to download a file and add observers for Fail,Success and Progress,but i get an error...
I alose checked on IOS and there it works.
How i tryed to download using observers
![Screenshot 2021-02-23 at 13 31 38](https://user-images.githubusercontent.com/33568841/108838110-debabe00-75db-11eb-9e00-671dffdabf68.png)

the exception :
![Screenshot 2021-02-23 at 13 31 59](https://user-images.githubusercontent.com/33568841/108838231-07db4e80-75dc-11eb-8c07-d1e5079d7bcb.png)

**Comment by TobiasBuchholz** [comment]
This was indeed a bug in the code. I've created a new version 1.0.4 with a fix for that problem. Please close this issue when you can confirm the fix works.

**Comment by geogian98** [comment]
> This was indeed a bug in the code. I've created a new version 1.0.4 with a fix for that problem. Please close this issue when you can confirm the fix works.

Thanks a lot for the quick fix. I appreciate it.  I will try it as soon as my firebase (quota issues) is working again and let you know.

**Comment by geogian98** [comment]
It works.Thank you!!! I really appreciate your work!
