### ISSUE TITLE
Nuget on Vs for Mac

### ISSUE THREAD

**Issue by ohumidk** [TobiasBuchholz/Plugin.Firebase#66]
Is this available on VS for mac. I just created a new MAUI project and once I add the Nuget.Package and add the code in the sample I will just get the following error.

Error CS0234: The type or namespace name 'Android' does not exist in the namespace 'Plugin.Firebase' (are you missing an assembly reference?) (CS0234)

**Comment by TobiasBuchholz** [comment]
Yes, this is available on VS for mac. Did you maybe forget to use the [conditional preprocessor directives](https://docs.microsoft.com/en-US/dotnet/csharp/language-reference/preprocessor-directives#conditional-compilation) like `#if ANDROID`?
