### ISSUE TITLE
Firestore: Couldn't put object of type System.Collections.Generic.Dictionary`2[System.String,System.Int64] into HashMap

### ISSUE THREAD

**Issue by Mataboge** [TobiasBuchholz/Plugin.Firebase#7]
### Test Enviroment:
Visual studio: V16.9.2
tested on android device,
have not tested on ios
xamarin forms V5.0.0.2012
plugin.Firebase V1.0.5

### Stacktrace

  at System.Collections.Generic.DictionaryExtension.Put (Java.Util.IMap this, System.Object key, System.Object value) [0x0024a] in <916f017aa0394a678344f82f4e06f803>:0 
  at System.Collections.Generic.DictionaryExtension.ToHashMap (System.Object this) [0x00050] in <916f017aa0394a678344f82f4e06f803>:0 
  at Plugin.Firebase.Android.Firestore.DocumentReferenceWrapper.SetDataAsync (System.Object data, Plugin.Firebase.Firestore.SetOptions options) [0x00094] in <916f017aa0394a678344f82f4e06f803>:0 

### Issue:
The firetore feature shows an error when when uploading a 'firestore-Map' ( a dictionary in the c# world) into the firestore database. 

### The exception message:

`Couldn't put object of type System.Collections.Generic.Dictionary`2[System.String,System.Int64] into HashMap`

### the code used to Add an object:

`
     var document = con.GetCollection(CollectionName).CreateDocument();
     
await document.SetDataAsync(model, SetOptions.Merge());
`
### the model used:

`
    public class TestUser : IFirestoreObject
    {
        [Preserve]
        public TestUser(){}

[FirestoreProperty("Score")]
 public long Score { get; set; }

[FirestoreProperty("Likes")]
public IList<string> Likes { get; set; }

[FirestoreProperty("SearchHistory")]
public Dictionary<string, long> SearchHistory { get; set; }
       }
`

### The initial conditions of the model:

`

            TestUser testUser = new TestUser();

            testUser.Likes = new List<string> { "1", "3", "25" };

            testUser.Score = 9;

            testUser.SearchHistory = new Dictionary<string, long>{ { "14", 5 }, { "45", 200 } };
`
the package seems to have a problem with casting dictionary to the android equivalent. when i remove the dictionary property, the data is uploading perfectly. When reading data (downloading from database), the plugin is able to cast the firestore-map back into the c# dictionary, the problem is casting c# dictionary to firestore-map when uploading.

The sample docs do not show an example for reading and writing an object with a map.

**Comment by TobiasBuchholz** [comment]
Thanks a lot for your detailed description of the issue. I've created a new version 1.0.6 which should fix the problem. If you can confirm it's fixed, please close this issue.

**Comment by Mataboge** [comment]
Thank you very for the swift response and action.
The error is fixed, but the dictionary is uploading an empty map. The loaded data inside the dictionary does not appear.

### Tested data:

`            testUser.Likes = new List<string> { "1", "3", "25" };
            testUser.Score = 9;
            testUser.Username = "zee";
            testUser.SearchNums = new Dictionary<string, long>{ { "14", 5 }, { "45", 200 } };
            testUser.ViewNums = new Dictionary<string, long>{ { "111", 15 }, { "10", 200 } };

            testUser.ViewNums.Add("20",(long)500);
`
### Resulting data online:

![firebase](https://user-images.githubusercontent.com/13901681/112067050-1fbcd880-8b70-11eb-9014-dc3f6267fa45.png)

**Comment by TobiasBuchholz** [comment]
Seems like my response was a litte too swift, sorry for that. I've created a new version 1.0.7 which should fix the issue.

**Comment by Mataboge** [comment]
This is perfect! 

Thank you very much, this is the best plugin.
