### ISSUE TITLE
Could not install nuget package on VS 2022

### ISSUE THREAD

**Issue by Shalafi280438** [TobiasBuchholz/Plugin.Firebase#70]
I tried to install the nuget package on Visual Studio 2022.

But i get the error:

> Could not find a part of the path 'C:\Users\Roman.nuget\packages\xamarin.firebase.ios.installations\8.10.0.1\lib\net6.0-ios15.4\Firebase.Installations.resources\FirebaseInstallations.xcframework\ios-arm64_i386_x86_64-simulator\FirebaseInstallations.framework\Headers\FirebaseInstallations-umbrella.h'.

I already set the LongPathsEnabled to 1 on the registry. But it doesn't work.

**Comment by TobiasBuchholz** [comment]
Try to add the package via `dotnet add package Plugin.Firebase`, see https://github.com/TobiasBuchholz/Plugin.Firebase/issues/65 for more information.

**Comment by Shalafi280438** [comment]
Big thx mate, it works.
Sorry i didn't see that closed Issus.

**Comment by TobiasBuchholz** [comment]
No problem! There was also already a hint in the installation section of the README.
I've made it a bit more prominent now ;)
