### ISSUE TITLE
Any way to build my Windows and Mac catalyst app with Plugin.Firebase

### ISSUE THREAD

**Issue by SarthakGz** [TobiasBuchholz/Plugin.Firebase#73]
I am totally fine with Plugin.Firebase does not support Windows and Mac catalyst but after installation Plugin.Firebase I am not able to run my windows app.

Is there any way I can use  Plugin.Firebase for android and iOS and still able to run my windows and Mac 

I had to do <TargetFrameworks>net6.0-android;net6.0-ios</TargetFrameworks> 
In order to able to build my project which means now windows and Mac anymore :(

**Comment by TobiasBuchholz** [comment]
I think this should be able by using [MSBuild conditions](https://learn.microsoft.com/de-de/visualstudio/msbuild/msbuild-conditions?view=vs-2022) in your `.csproj file` like this:

```c#
<ItemGroup Condition="'$(TargetFramework)' == 'net6.0-ios' OR '$(TargetFramework)' == 'net6.0-android'">
    <PackageReference Include="Plugin.Firebase" Version="1.2.0" />
</ItemGroup>

```

Also in your code files you can add [preprocessor directives](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives#conditional-compilation) where necessary. Hope this helps!
