### ISSUE TITLE
Couldn't retrieve FCM token

### ISSUE THREAD

**Issue by ThomasBernard03** [TobiasBuchholz/Plugin.Firebase#74]
Hello, I have a problem with ```await CrossFirebaseCloudMessaging.Current.GetTokenAsync();```

This line throw an Exception : Couldn't retrieve FCM token

I'm using .NET Maui, VS Mac and debugging on Iphone 13 Simulator

StackTrace : ```at Plugin.Firebase.CloudMessaging.FirebaseCloudMessagingImplementation.GetTokenAsync()
   at InitManage.ViewModels.Login.LoginViewModel.OnLoginCommand() in /Users/thomasbernard/Desktop/INIT Mobile .nosync/InitManage/InitManage/ViewModels/Login/LoginViewModel.cs:line 66```

**Comment by TobiasBuchholz** [comment]
Hi, I would guess this happens because Cloud Messages are not supported on iOS simulators. Did you try the same code on a device as well?

**Comment by ThomasBernard03** [comment]
Yes probably, I'll try this week on a real device and I'll let you know

**Comment by canperk** [comment]
You didn't let us know :) @ThomasBernard03
