### ISSUE TITLE
Firebase Realtime feature 

### ISSUE THREAD

**Issue by Cizzl** [TobiasBuchholz/Plugin.Firebase#75]
Would it be possible to add a feature to use the realtime database?

**Comment by SarthakGz** [comment]
@Cizzl you can use https://www.nuget.org/packages/FirebaseDatabase.net library for that

**Comment by TobiasBuchholz** [comment]
Yes, it would be possible, but I'm not planning on adding support for the realtime database since firestore is the alternative approach and suffices my needs. But you are very welcome to write the wrappers around the native realtime sdks yourself and create a PR :)
