### ISSUE TITLE
Custom notification icon shows only when i am in app

### ISSUE THREAD

**Issue by lukas8092** [TobiasBuchholz/Plugin.Firebase#76]
I am using this to change notification icon like it was on this website [Link](https://www.andreasnesheim.no/push-notifications-in-net-maui-with-firebase/)
In MainActivity.cs `FirebaseCloudMessagingImplementation.SmallIconRef = Resource.Drawable.notify_icon;`
```
private void CreateNotificationChannel()
    {
        var channelId = $"{PackageName}.general";
        var notificationManager = (NotificationManager)GetSystemService(NotificationService);
        var channel = new NotificationChannel(channelId, "General", NotificationImportance.Default);
        notificationManager.CreateNotificationChannel(channel);
        FirebaseCloudMessagingImplementation.ChannelId = channelId;
        FirebaseCloudMessagingImplementation.SmallIconRef = Resource.Drawable.notify_icon;
    }
```
My custom icon show up only when i am in the app, when app is on background or its not running, it's only show that default white square icon

**Comment by TobiasBuchholz** [comment]
You'll need to add the reference to the icon also to your `AndroidManifest.xml` like this:
```xml 
<meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/ic_push_small" />
```

You can take a look at the [sample app](https://github.com/TobiasBuchholz/Plugin.Firebase/blob/5bdf758c1b1683cf614a1e1e895a043af6864819/sample/Playground/Platforms/Android/AndroidManifest.xml#L24).

**Comment by lukas8092** [comment]
Thank you, i didn't notice it.
