### ISSUE TITLE
.net7 support

### ISSUE THREAD

**Issue by JoshZA** [TobiasBuchholz/Plugin.Firebase#79]
Is .net 7 support in the pipeline?

**Comment by TobiasBuchholz** [comment]
When the underlying packages are supporting it, I'll update the plugin as well.

**Comment by radderz** [comment]
@TobiasBuchholz Is this still the case that the underlying packages don't support .NET 7 Maui.NET? We are writing a Blazor Maui App (.NET 7) and would like to be able to use this package :)
