### ISSUE TITLE
Firestore: Requesting Document Id Attribute

### ISSUE THREAD

**Issue by Mataboge** [TobiasBuchholz/Plugin.Firebase#8]
An attribute for the document Id is necessary when reading data from Firestore if having the id as a class property.
The .Net Firestore implementation has that attribute as seen below from [here](https://googleapis.github.io/google-cloud-dotnet/docs/Google.Cloud.Firestore/datamodel.html)

    `[FirestoreDocumentId]`
    `public string MyIdPropertyName { get; set; }`

When dealing with a large set of data it becomes tedious to update your id property from Document.Reference.Id for each document. 

Please add the attribute that will automatically copy the document id into a single property in the class model.

**Comment by TobiasBuchholz** [comment]
Makes sense, I've created a new `[FirestoreDocumentId]` attribute. A property in the class model decorated with this attribute will automatically receive the document's id as value. It's contained in version 1.0.7.
