### ISSUE TITLE
Deploying to iOS using Xcode 14.1

### ISSUE THREAD

**Issue by ahmad-hosseini** [TobiasBuchholz/Plugin.Firebase#86]
We're trying to deploy our application to TestFlight but we keep getting an error when using this package. Here's one of the errors:

`ITMS-90482: Invalid Executable - The executable 'MyMobileApp.app/Frameworks/FirebaseCore.framework/FirebaseCore' contains bitcode. `

It seems the package has enabled bitcode, whilst we haven't. This mix isn't allowed and in Xcode 14 bitcode was deprecated. Is there anyway we can turn it off for this package or has anyone managed to get around this? 

Xcode version: 14.1
VM: macOS-12

**Comment by TobiasBuchholz** [comment]
Hi @ahmad-hosseini, this package is just a crossplatform wrapper around the native firebase packages provided by Microsoft. You might find an answer to your question at their [repository](https://github.com/xamarin/GoogleApisForiOSComponents) or you can ask it again there. Hope this helps!

**Comment by ahmad-hosseini** [comment]
Hey @TobiasBuchholz that is helpful.

For anyone else having the same issue, it is currently being tracked here:
https://github.com/xamarin/GoogleApisForiOSComponents/issues/578

**Comment by ahmad-hosseini** [comment]
<details>
<summary>Details</summary>



</details>
