### ISSUE TITLE
Firstore Utc Offset gets lost

### ISSUE THREAD

**Issue by Lyror** [TobiasBuchholz/Plugin.Firebase#88]
I'm currently trying to fetch some time data from firestore.

``` CSharp
public async Task<IEnumerable<IDocumentSnapshot<Models.Ticket>>> GetAllAsync(string userId)
{
	var ticketRef = firestore.GetCollection(FirestorePathHelper.GetTicketsCollectionPath(userId));
	var tickets = await ticketRef.GetDocumentsAsync<Models.Ticket>();
	return tickets.Documents;
}
```
Models.Ticket Properties
```CSharp
[FirestoreProperty("start")]
public DateTimeOffset Start { get; set; }

[FirestoreProperty("end")]
public DateTimeOffset End { get; set; }
```
firestore entity
![image](https://user-images.githubusercontent.com/10835078/199244946-97cabbda-7062-4bb3-86dc-6fd23b77925f.png)

The problem is that if I do `Start.ToLocalTime()` the time didn't change. I think the UTC Offset is gone at one point. 

Would it be possible to keep the time zone? How else would I know which time zone "Start" or "End" comes from?

**Comment by vhugogarcia** [comment]
@Lyror if you would like to keep the timezone and use the local time zone of the user, I recommend you to use something like this: 
```csharp
[FirestoreProperty("joined_at")]
public DateTimeOffset JoinedAt { get; set; }

// Gets a DateTime value that represents the local date and time of the current DateTimeOffset object.
public DateTime Joined => JoinedAt.LocalDateTime;
```

@TobiasBuchholz by reviewing this issue, I noticed that this issue **is not** related with the plugin itself, and I believe we can safely close this issue.

Regards,
Victor
