### ISSUE TITLE
Any plans to separate functionality into multiple nuget packages?

### ISSUE THREAD

**Issue by SailorTurkey** [TobiasBuchholz/Plugin.Firebase#9]
As its, this project creating a very large ipa file for IOS size, 
Most people just need messaging and analytics (also crashlytics) support.

Can you / Will you / Are you planning to at least make a nuget containing only those?

**Comment by TobiasBuchholz** [comment]
No, there are no plans to create nugets containing only specific parts of the plugin.

I'm following the approach of the Xamarin.Essentials plugin to just include everything and let the linker remove anything that's not used. Until now I haven't done anything particular to achieve that except making sure everything works when the linker is activated. So to be honest I don't know what gets stripped away and what does not, so tips and tricks are welcome :)

I've done some little testing on this issue by creating a new Xamarin.Forms Shell project and comparing the .ipa file sizes:
- project without the plugin: 10 MB
- project with plugin and the linker set to 'Don't link': 39,6 MB
- project with plugin and the linker set to 'Sdk only': 21,4 MB
- project with plugin and the linker set to 'All': 20,2 MB

So the plugin seems to add around 10 MB extra to the .ipa file, but in times of wifi everywhere and 4G/5G this isn't a big deal in my opinion.
