### ISSUE TITLE
Set FirestoreSettings, NetworkAccess, ClearLocalCache

### ISSUE THREAD

**Issue by SeriousM** [TobiasBuchholz/Plugin.Firebase#93]
* Is there a way to set the FirestoreSettings, in particular the CacheSizeBytes?
* Is there support to control [network access](https://firebase.google.com/docs/firestore/manage-data/enable-offline#disable_and_enable_network_access)?
* Can we delete the local cache? [Android](https://firebase.google.com/support/release-notes/android#firestore_v21.1.0), [iOS](https://firebase.google.com/support/release-notes/ios#cloud-firestore_53)
  * Can you expose the local db so one could get a copy for debug insights?

**Comment by TobiasBuchholz** [comment]
> Is there a way to set the FirestoreSettings, in particular the CacheSizeBytes?

Yes, you can set the `FirestoreSettings` on the `IFirebaseFirestore` instance. In your case it would look like this:
```c#
var firestore = CrossFirebaseFirestore.Current;
var settings = firestore.Settings;
firestore.Settings = new FirestoreSettings(
    host: settings.Host,
    isPersistenceEnabled: settings.IsPersistenceEnabled,
    isSslEnabled: settings.IsSslEnabled,
    cacheSizeBytes: 1337L);

```

> Is there support to control [network access](https://firebase.google.com/docs/firestore/manage-data/enable-offline#disable_and_enable_network_access)?
Can we delete the local cache? [Android](https://firebase.google.com/support/release-notes/android#firestore_v21.1.0), [iOS](https://firebase.google.com/support/release-notes/ios#cloud-firestore_53)

I've just created a new version 1.2.2 which implements those methods. You can find them on the `IFirebaseFirestore` instance.

> Can you expose the local db so one could get a copy for debug insights?

As far as I know the native libraries don't offer any possibility to do something like that but please let me know if there is.

**Comment by SeriousM** [comment]
I wasn't aware that I'm supposed to _replace_ the settings object as I thought it might get cached somewhere and the new instance wouldn't take effect. Maybe pointing it out in a documentation on `firestore.Settings` would help.

Thank you very much for extending the proxy to the native libraries in https://github.com/TobiasBuchholz/Plugin.Firebase/commit/26330773ab27e3f41bab1edf9551790bcf3b926a! That really helps!

> > Can you expose the local db so one could get a copy for debug insights?
> 
> As far as I know the native libraries don't offer any possibility to do something like that but please let me know if there is.

No native way so far.
For anyone whos interested: You can query all root collections and documents (by iterating the known paths) by requesting only cached items and then put them into a json file.
