### ISSUE TITLE
How can i use click action on received messag?

### ISSUE THREAD

**Issue by binhtt6** [TobiasBuchholz/Plugin.Firebase#98]
Hi, as the question: i want to implement funtion when i click on received message, my app will navigate to specific page ( for both case: razor page and xaml page) instead of Main Activity.
How can i do this?
Thanks

**Comment by TobiasBuchholz** [comment]
Hi, when sending your push notification from the server you can add custom payload fields to the `data` object:

```json
{
 "to" : "/topics/news",
 "collapse_key" : "type_a",
 "mutable_content": true,
  "notification" : {
     "body" : "body of topic notification",
     "title": "title of topic notification"
 },
 "data" : {
     "navigation_path" : "path/to/page"
 }
}
```

Then in the client you can extract that information from the `FCMNotification` object received by the `NotificationTapped` handler (and navigate to the page depending on your implementation):

```c#
_firebaseCloudMessaging.NotificationTapped += (sender, args) => {
    if(args.Notification.Data.ContainsKey("navigation_path")) {
        var path = args.Notification.Data["navigation_path"];
        NavigateTo(path);
    }
};

```

**Comment by binhtt6** [comment]
Thanks for your response. But i got this message, and stuck after Oncreate in MainActivity? Do yoy have any idea?

![image](https://user-images.githubusercontent.com/30441291/205612129-1ad71664-99f8-43e3-bd3d-3bc1db3e4d9a.png)
![image](https://user-images.githubusercontent.com/30441291/205612246-acf8a5a0-5424-4609-9c81-b7ffff8269e8.png)
![image](https://user-images.githubusercontent.com/30441291/205612357-5bb9ad1d-c1d6-4bda-9968-b43bced015f6.png)
